import type { FunctionSignature } from '../../completion'

export const functions: string[] = [
    'ABS',
    'ACOS',
    'AGE',
    'AREA',
    'ARRAY_AGG',
    'ARRAY_APPEND',
    'ARRAY_CAT',
    'ARRAY_DIMS',
    'ARRAY_FILL',
    'ARRAY_LENGTH',
    'ARRAY_LOWER',
    'ARRAY_NDIMS',
    'ARRAY_POSITION',
    'ARRAY_POSITIONS',
    'ARRAY_PREPEND',
    'ARRAY_REMOVE',
    'ARRAY_REPLACE',
    'ARRAY_TO_STRING',
    'ARRAY_UPPER',
    'ASCII',
    'ASIN',
    'ATAN',
    'ATAN2',
    'AVG',
    'BIT_AND',
    'BIT_OR',
    'BOOL_AND',
    'BOOL_OR',
    'BTRIM',
    'CARDINALITY',
    'CASE',
    'CBRT',
    'CEIL',
    'CEILING',
    'CENTER',
    'CHAR_LENGTH',
    'CHARACTER_LENGTH',
    'CHR',
    'CLOCK_TIMESTAMP',
    'COALESCE',
    'CONCAT',
    'CONCAT_WS',
    'COS',
    'COT',
    'COUNT',
    'CUME_DIST',
    'CURRENT_CATALOG',
    'CURRENT_DATABASE',
    'CURRENT_DATE',
    'CURRENT_SCHEMA',
    'CURRENT_TIME',
    'CURRENT_TIMESTAMP',
    'CURRENT_USER',
    'DATE_PART',
    'DATE_TRUNC',
    'DEGREES',
    'DENSE_RANK',
    'DIAMETER',
    'DIV',
    'EVERY',
    'EXP',
    'EXTRACT',
    'FACTORIAL',
    'FIRST_VALUE',
    'FLOOR',
    'FORMAT',
    'GCD',
    'GENERATE_SERIES',
    'GENERATE_SUBSCRIPTS',
    'GREATEST',
    'HAS_DATABASE_PRIVILEGE',
    'HAS_FUNCTION_PRIVILEGE',
    'HAS_SCHEMA_PRIVILEGE',
    'HAS_TABLE_PRIVILEGE',
    'HEIGHT',
    'INITCAP',
    'INSTR',
    'ISCLOSED',
    'ISFINITE',
    'ISOPEN',
    'JSON_AGG',
    'JSON_ARRAY_LENGTH',
    'JSON_BUILD_ARRAY',
    'JSON_BUILD_OBJECT',
    'JSON_EACH',
    'JSON_EACH_TEXT',
    'JSON_EXTRACT_PATH',
    'JSON_EXTRACT_PATH_TEXT',
    'JSON_OBJECT_AGG',
    'JSON_OBJECT_KEYS',
    'JSON_POPULATE_RECORD',
    'JSON_POPULATE_RECORDSET',
    'JSON_STRIP_NULLS',
    'JSON_TO_RECORD',
    'JSON_TO_RECORDSET',
    'JSON_TYPEOF',
    'JSONB_AGG',
    'JSONB_ARRAY_LENGTH',
    'JSONB_BUILD_ARRAY',
    'JSONB_BUILD_OBJECT',
    'JSONB_EACH',
    'JSONB_EACH_TEXT',
    'JSONB_EXTRACT_PATH',
    'JSONB_EXTRACT_PATH_TEXT',
    'JSONB_INSERT',
    'JSONB_OBJECT_AGG',
    'JSONB_OBJECT_KEYS',
    'JSONB_PRETTY',
    'JSONB_SET',
    'JSONB_STRIP_NULLS',
    'JSONB_TYPEOF',
    'JUSTIFY_DAYS',
    'JUSTIFY_HOURS',
    'JUSTIFY_INTERVAL',
    'LAG',
    'LAST_VALUE',
    'LCM',
    'LEAD',
    'LEAST',
    'LEFT',
    'LENGTH',
    'LN',
    'LOCALTIME',
    'LOCALTIMESTAMP',
    'LOG',
    'LOG10',
    'LOWER',
    'LPAD',
    'LTRIM',
    'MAKE_DATE',
    'MAKE_INTERVAL',
    'MAKE_TIME',
    'MAKE_TIMESTAMP',
    'MAKE_TIMESTAMPTZ',
    'MAX',
    'MD5',
    'MIN',
    'MIN_SCALE',
    'MOD',
    'NOW',
    'NPOINTS',
    'NTILE',
    'NTH_VALUE',
    'NULLIF',
    'OCTET_LENGTH',
    'OVERLAY',
    'PARSE_IDENT',
    'PCLOSE',
    'PERCENT_RANK',
    'PG_CANCEL_BACKEND',
    'PG_CLIENT_ENCODING',
    'PG_COLUMN_SIZE',
    'PG_DATABASE_SIZE',
    'PG_INDEXES_SIZE',
    'PG_RELOAD_CONF',
    'PG_ROTATE_LOGFILE',
    'PG_SLEEP',
    'PG_TABLE_SIZE',
    'PG_TERMINATE_BACKEND',
    'PG_TOTAL_RELATION_SIZE',
    'PI',
    'POPEN',
    'POSITION',
    'POWER',
    'QUOTE_IDENT',
    'QUOTE_LITERAL',
    'RADIANS',
    'RADIUS',
    'RANDOM',
    'RANGE_AGG',
    'RANGE_INTERSECT_AGG',
    'RANK',
    'REGEXP_COUNT',
    'REGEXP_INSTR',
    'REGEXP_LIKE',
    'REGEXP_MATCH',
    'REGEXP_REPLACE',
    'REGEXP_SPLIT_TO_ARRAY',
    'REGEXP_SPLIT_TO_TABLE',
    'REPEAT',
    'REPLACE',
    'REVERSE',
    'RIGHT',
    'ROUND',
    'ROW_NUMBER',
    'RPAD',
    'RTRIM',
    'SCALE',
    'SESSION_USER',
    'SETSEED',
    'SIGN',
    'SIN',
    'SPLIT_PART',
    'SQRT',
    'STARTS_WITH',
    'STATEMENT_TIMESTAMP',
    'STDDEV',
    'STDDEV_POP',
    'STDDEV_SAMP',
    'STRING_AGG',
    'STRING_TO_ARRAY',
    'STRPOS',
    'SUBSTR',
    'SUBSTRING',
    'SUM',
    'TAN',
    'TIMEOFDAY',
    'TO_ASCII',
    'TO_HEX',
    'TRANSACTION_TIMESTAMP',
    'TRANSLATE',
    'TRIM',
    'TRIM_SCALE',
    'TRUNC',
    'UNNEST',
    'UPPER',
    'USER',
    'VAR_POP',
    'VAR_SAMP',
    'VARIANCE',
    'WIDTH',
    'WIDTH_BUCKET',
    'XMLAGG',
]

export const functionSignatures: FunctionSignature[] = [
    { name: 'STRING_AGG', params: ['expression text', 'delimiter text', 'ORDER BY sort_expression'], returnType: 'text', description: '将多个字符串连接成一个字符串', category: 'aggregate' },
    { name: 'ARRAY_AGG', params: ['expression anynonarray', 'ORDER BY sort_expression'], returnType: 'array', description: '将值聚合为数组', category: 'aggregate' },
    { name: 'GENERATE_SERIES', params: ['start integer', 'stop integer', 'step integer'], returnType: 'setof integer', description: '生成一个整数序列', category: 'table' },
    { name: 'JSONB_BUILD_OBJECT', params: ['key text', 'value any', '...'], returnType: 'jsonb', description: '从键值对构建 JSONB 对象', category: 'json' },
    { name: 'AVG', params: ['expression'], returnType: 'double precision', description: '返回平均值', category: 'aggregate' },
    { name: 'SUM', params: ['expression'], returnType: 'numeric', description: '返回总和', category: 'aggregate' },
    { name: 'COUNT', params: ['*|expression'], returnType: 'bigint', description: '返回行数或非 NULL 行数', category: 'aggregate' },
    { name: 'MAX', params: ['expression'], returnType: 'same as input', description: '返回最大值', category: 'aggregate' },
    { name: 'MIN', params: ['expression'], returnType: 'same as input', description: '返回最小值', category: 'aggregate' },
    { name: 'STDDEV', params: ['expression'], returnType: 'double precision', description: '返回样本标准差', category: 'aggregate' },
    { name: 'STDDEV_POP', params: ['expression'], returnType: 'double precision', description: '返回总体标准差', category: 'aggregate' },
    { name: 'STDDEV_SAMP', params: ['expression'], returnType: 'double precision', description: '返回样本标准差', category: 'aggregate' },
    { name: 'VARIANCE', params: ['expression'], returnType: 'double precision', description: '返回样本方差', category: 'aggregate' },
    { name: 'VAR_POP', params: ['expression'], returnType: 'double precision', description: '返回总体方差', category: 'aggregate' },
    { name: 'VAR_SAMP', params: ['expression'], returnType: 'double precision', description: '返回样本方差', category: 'aggregate' },
    { name: 'BOOL_AND', params: ['expression boolean'], returnType: 'boolean', description: '所有值为真时返回真', category: 'aggregate' },
    { name: 'BOOL_OR', params: ['expression boolean'], returnType: 'boolean', description: '任一值为真时返回真', category: 'aggregate' },
    { name: 'BIT_AND', params: ['expression'], returnType: 'bigint', description: '按位与聚合', category: 'aggregate' },
    { name: 'BIT_OR', params: ['expression'], returnType: 'bigint', description: '按位或聚合', category: 'aggregate' },
    { name: 'EVERY', params: ['expression boolean'], returnType: 'boolean', description: 'BOOL_AND 的别名', category: 'aggregate' },
    { name: 'JSON_AGG', params: ['expression'], returnType: 'json', description: '将值聚合为 JSON 数组', category: 'aggregate' },
    { name: 'JSONB_AGG', params: ['expression'], returnType: 'jsonb', description: '将值聚合为 JSONB 数组', category: 'aggregate' },
    { name: 'JSON_OBJECT_AGG', params: ['key expression', 'value expression'], returnType: 'json', description: '将键值对聚合为 JSON 对象', category: 'aggregate' },
    { name: 'JSONB_OBJECT_AGG', params: ['key expression', 'value expression'], returnType: 'jsonb', description: '将键值对聚合为 JSONB 对象', category: 'aggregate' },
    { name: 'XMLAGG', params: ['expression xml'], returnType: 'xml', description: '将 XML 片段聚合', category: 'aggregate' },
    { name: 'RANGE_AGG', params: ['expression anyrange'], returnType: 'anymultirange', description: '将范围值聚合为多范围', category: 'aggregate' },
    { name: 'RANGE_INTERSECT_AGG', params: ['expression anyrange'], returnType: 'anyrange|anymultirange', description: '计算范围交集聚合', category: 'aggregate' },
    { name: 'ARRAY_APPEND', params: ['array anyarray', 'element anyelement'], returnType: 'anyarray', description: '向数组末尾追加元素', category: 'array' },
    { name: 'ARRAY_CAT', params: ['array1 anyarray', 'array2 anyarray'], returnType: 'anyarray', description: '连接两个数组', category: 'array' },
    { name: 'ARRAY_LENGTH', params: ['array anyarray', 'dimension int'], returnType: 'int', description: '返回数组指定维度的长度', category: 'array' },
    { name: 'ARRAY_REMOVE', params: ['array anyarray', 'element anyelement'], returnType: 'anyarray', description: '从数组中删除所有等于指定值的元素', category: 'array' },
    { name: 'ARRAY_REPLACE', params: ['array anyarray', 'from anyelement', 'to anyelement'], returnType: 'anyarray', description: '替换数组中的元素', category: 'array' },
    { name: 'ARRAY_TO_STRING', params: ['array anyarray', 'delimiter text', 'null_string text'], returnType: 'text', description: '将数组转为分隔字符串', category: 'array' },
    { name: 'STRING_TO_ARRAY', params: ['string text', 'delimiter text', 'null_string text'], returnType: 'text[]', description: '将分隔字符串转为数组', category: 'array' },
    { name: 'UNNEST', params: ['array anyarray|setof anyelement'], returnType: 'setof anyelement', description: '将数组展开为多行', category: 'array' },
    { name: 'CARDINALITY', params: ['array anyarray'], returnType: 'int', description: '返回数组元素总数', category: 'array' },
    { name: 'REGEXP_MATCH', params: ['string text', 'pattern text', 'flags text'], returnType: 'text[]', description: '返回匹配正则表达式的子串数组', category: 'string' },
    { name: 'REGEXP_REPLACE', params: ['string text', 'pattern text', 'replacement text', 'flags text'], returnType: 'text', description: '替换匹配正则表达式的子串', category: 'string' },
    { name: 'REGEXP_SPLIT_TO_ARRAY', params: ['string text', 'pattern text', 'flags text'], returnType: 'text[]', description: '按正则拆分字符串为数组', category: 'string' },
    { name: 'REGEXP_SPLIT_TO_TABLE', params: ['string text', 'pattern text', 'flags text'], returnType: 'setof text', description: '按正则拆分字符串为多行', category: 'string' },
    { name: 'DATE_TRUNC', params: ['field text', 'source timestamp|interval'], returnType: 'timestamp|interval', description: '将时间截断到指定精度', category: 'date' },
    { name: 'DATE_PART', params: ['field text', 'source timestamp|interval'], returnType: 'double precision', description: '从时间中提取指定字段的值', category: 'date' },
    { name: 'EXTRACT', params: ['field from source'], returnType: 'double precision', description: '从时间中提取指定字段的值', category: 'date' },
    { name: 'AGE', params: ['timestamp', 'timestamp'], returnType: 'interval', description: '计算两个时间戳之间的时间差', category: 'date' },
    { name: 'NOW', params: [], returnType: 'timestamp with time zone', description: '返回当前事务开始时间', category: 'date' },
    { name: 'PG_SLEEP', params: ['seconds double precision'], returnType: 'void', description: '暂停指定秒数', category: 'system' },
    { name: 'PG_TABLE_SIZE', params: ['relation regclass'], returnType: 'bigint', description: '返回表使用的磁盘空间', category: 'system' },
    { name: 'PG_DATABASE_SIZE', params: ['oid|name'], returnType: 'bigint', description: '返回数据库使用的磁盘空间', category: 'system' },
    { name: 'PG_TERMINATE_BACKEND', params: ['pid integer'], returnType: 'boolean', description: '终止指定 PID 的后端进程', category: 'system' },
    { name: 'ROW_NUMBER', params: [], returnType: 'bigint', description: '返回行号（从 1 开始）', category: 'window' },
    { name: 'RANK', params: [], returnType: 'bigint', description: '返回排序名次（相同值同名次，有间隔）', category: 'window' },
    { name: 'DENSE_RANK', params: [], returnType: 'bigint', description: '返回排序名次（相同值同名次，无间隔）', category: 'window' },
    { name: 'LAG', params: ['value anyelement', 'offset integer', 'default anyelement'], returnType: 'same as value', description: '返回当前行之前 offset 行的值', category: 'window' },
    { name: 'LEAD', params: ['value anyelement', 'offset integer', 'default anyelement'], returnType: 'same as value', description: '返回当前行之后 offset 行的值', category: 'window' },
    { name: 'FIRST_VALUE', params: ['value anyelement'], returnType: 'same as value', description: '返回窗口内第一行的值', category: 'window' },
    { name: 'LAST_VALUE', params: ['value anyelement'], returnType: 'same as value', description: '返回窗口内最后一行的值', category: 'window' },
    { name: 'NTH_VALUE', params: ['value anyelement', 'nth integer'], returnType: 'same as value', description: '返回窗口内第 n 行的值', category: 'window' },
    { name: 'NTILE', params: ['num_buckets integer'], returnType: 'integer', description: '将行分配到指定数量的桶中', category: 'window' },
    { name: 'CUME_DIST', params: [], returnType: 'double precision', description: '返回累积分布值', category: 'window' },
    { name: 'PERCENT_RANK', params: [], returnType: 'double precision', description: '返回相对排名百分比', category: 'window' },
    { name: 'COALESCE', params: ['value anyelement', '...'], returnType: 'same as first non-null', description: '返回第一个非 NULL 值', category: 'conditional' },
    { name: 'NULLIF', params: ['value1 anyelement', 'value2 anyelement'], returnType: 'same as value1', description: '若两值相等则返回 NULL', category: 'conditional' },
    { name: 'GREATEST', params: ['value anyelement', '...'], returnType: 'same as input', description: '返回所有参数中的最大值', category: 'conditional' },
    { name: 'LEAST', params: ['value anyelement', '...'], returnType: 'same as input', description: '返回所有参数中的最小值', category: 'conditional' },
    { name: 'CONCAT', params: ['str1 text|anynonarray', 'str2 text|anynonarray', '...'], returnType: 'text', description: '连接字符串', category: 'string' },
    { name: 'CONCAT_WS', params: ['sep text', 'str1 text|anynonarray', '...'], returnType: 'text', description: '使用分隔符连接字符串', category: 'string' },
    { name: 'FORMAT', params: ['formatstr text', '...'], returnType: 'text', description: '格式化字符串（类似 sprintf）', category: 'string' },
    { name: 'ABS', params: ['value numeric'], returnType: 'numeric', description: '返回绝对值', category: 'math' },
    { name: 'ROUND', params: ['value numeric', 'scale integer'], returnType: 'numeric', description: '四舍五入到指定小数位', category: 'math' },
    { name: 'POWER', params: ['base numeric', 'exponent numeric'], returnType: 'numeric', description: '返回 base 的 exponent 次幂', category: 'math' },
    { name: 'AREA', params: ['path'], returnType: 'double precision', description: '返回路径图形的面积', category: 'geometric' },
    { name: 'CENTER', params: ['object'], returnType: 'point', description: '返回几何图形的中心点', category: 'geometric' },
    { name: 'LENGTH', params: ['path|line|lseg|box'], returnType: 'double precision', description: '返回路径/线段的长度', category: 'geometric' },
]