import type { FunctionSignature } from '../../completion'

export const functions: string[] = [
    // aggregate
    'ANY_VALUE',
    'APPROX_COUNT_DISTINCT',
    'APPROX_QUANTILES',
    'APPROX_TOP_COUNT',
    'APPROX_TOP_SUM',
    'ARRAY_AGG',
    'ARRAY_CONCAT_AGG',
    'AVG',
    'BIT_AND',
    'BIT_OR',
    'BIT_XOR',
    'COUNT',
    'COUNTIF',
    'COVAR_POP',
    'COVAR_SAMP',
    'HLL_COUNT_INIT',
    'HLL_COUNT_MERGE',
    'HLL_COUNT_EXTRACT',
    'LOGICAL_AND',
    'LOGICAL_OR',
    'MAX',
    'MIN',
    'STRING_AGG',
    'SUM',
    'STDDEV_POP',
    'STDDEV_SAMP',
    'STDDEV',
    'VAR_POP',
    'VAR_SAMP',
    'VARIANCE',

    // array
    'ARRAY',
    'ARRAY_AGG',
    'ARRAY_CONCAT',
    'ARRAY_CONCAT_AGG',
    'ARRAY_LENGTH',
    'ARRAY_REVERSE',
    'ARRAY_SLICE',
    'ARRAY_TO_STRING',
    'GENERATE_ARRAY',
    'GENERATE_DATE_ARRAY',
    'GENERATE_TIMESTAMP_ARRAY',
    'OFFSET',
    'ORDINAL',
    'SAFE_OFFSET',
    'SAFE_ORDINAL',

    // date
    'CURRENT_DATE',
    'CURRENT_DATETIME',
    'CURRENT_TIME',
    'CURRENT_TIMESTAMP',
    'DATE',
    'DATE_ADD',
    'DATE_DIFF',
    'DATE_FROM_UNIX_DATE',
    'DATE_SUB',
    'DATE_TRUNC',
    'DATETIME',
    'DATETIME_ADD',
    'DATETIME_DIFF',
    'DATETIME_SUB',
    'DATETIME_TRUNC',
    'EXTRACT',
    'FORMAT_DATE',
    'FORMAT_DATETIME',
    'FORMAT_TIME',
    'FORMAT_TIMESTAMP',
    'GENERATE_DATE_ARRAY',
    'LAST_DAY',
    'PARSE_DATE',
    'PARSE_DATETIME',
    'PARSE_TIME',
    'PARSE_TIMESTAMP',
    'TIME',
    'TIME_ADD',
    'TIME_DIFF',
    'TIME_SUB',
    'TIME_TRUNC',
    'TIMESTAMP',
    'TIMESTAMP_ADD',
    'TIMESTAMP_DIFF',
    'TIMESTAMP_MICROS',
    'TIMESTAMP_MILLIS',
    'TIMESTAMP_SECONDS',
    'TIMESTAMP_SUB',
    'TIMESTAMP_TRUNC',
    'UNIX_DATE',
    'UNIX_MICROS',
    'UNIX_MILLIS',
    'UNIX_SECONDS',

    // string
    'ASCII',
    'BEGINS_WITH',
    'BYTE_LENGTH',
    'CHAR_LENGTH',
    'CHARACTER_LENGTH',
    'CHR',
    'CODE_POINTS_TO_BYTES',
    'CODE_POINTS_TO_STRING',
    'COLLATE',
    'CONCAT',
    'CONTAINS',
    'CONTAINS_SUBSTR',
    'ENDS_WITH',
    'FORMAT',
    'FROM_BASE32',
    'FROM_BASE64',
    'FROM_HEX',
    'INITCAP',
    'INSTR',
    'LEFT',
    'LENGTH',
    'LIKE',
    'LOWER',
    'LPAD',
    'LTRIM',
    'NORMALIZE',
    'NORMALIZE_AND_CASEFOLD',
    'OCTET_LENGTH',
    'REGEXP_CONTAINS',
    'REGEXP_EXTRACT',
    'REGEXP_EXTRACT_ALL',
    'REGEXP_INSTR',
    'REGEXP_REPLACE',
    'REGEXP_SUBSTR',
    'REPLACE',
    'REPEAT',
    'REVERSE',
    'RIGHT',
    'RPAD',
    'RTRIM',
    'SAFE_CONVERT_BYTES_TO_STRING',
    'SOUNDEX',
    'SPLIT',
    'STARTS_WITH',
    'STRPOS',
    'SUBSTR',
    'SUBSTRING',
    'TO_BASE32',
    'TO_BASE64',
    'TO_CODE_POINTS',
    'TO_HEX',
    'TRANSLATE',
    'TRIM',
    'UNICODE',
    'UPPER',

    // conversion
    'BOOL',
    'CAST',
    'DATE',
    'DATETIME',
    'FLOAT64',
    'INT64',
    'NUMERIC',
    'PARSE_BIGNUMERIC',
    'PARSE_NUMERIC',
    'SAFE_CAST',
    'STRING',
    'TIME',
    'TIMESTAMP',
    'TO_JSON',
    'TO_JSON_STRING',

    // json
    'JSON_ARRAY',
    'JSON_EXTRACT',
    'JSON_EXTRACT_ARRAY',
    'JSON_EXTRACT_SCALAR',
    'JSON_EXTRACT_STRING_ARRAY',
    'JSON_OBJECT',
    'JSON_QUERY',
    'JSON_QUERY_ARRAY',
    'JSON_SET',
    'JSON_STRIP_NULLS',
    'JSON_TYPE',
    'JSON_VALUE',
    'JSON_VALUE_ARRAY',
    'LAX_BOOL',
    'LAX_FLOAT64',
    'LAX_INT64',
    'LAX_STRING',
    'PARSE_JSON',
    'TO_JSON',
    'TO_JSON_STRING',

    // math
    'ABS',
    'ACOS',
    'ACOSH',
    'ASIN',
    'ASINH',
    'ATAN',
    'ATAN2',
    'ATANH',
    'BIGNUMERIC',
    'CEIL',
    'CEILING',
    'COS',
    'COSH',
    'COT',
    'COTH',
    'CSC',
    'CSCH',
    'DEGREES',
    'EXP',
    'FLOOR',
    'GREATEST',
    'IEEE_DIVIDE',
    'IS_INF',
    'IS_NAN',
    'LEAST',
    'LN',
    'LOG',
    'LOG10',
    'MOD',
    'PI',
    'POW',
    'POWER',
    'RADIANS',
    'RAND',
    'RANGE_BUCKET',
    'ROUND',
    'SAFE_ADD',
    'SAFE_DIVIDE',
    'SAFE_MULTIPLY',
    'SAFE_NEGATE',
    'SAFE_SUBTRACT',
    'SEC',
    'SECH',
    'SIGN',
    'SIN',
    'SINH',
    'SQRT',
    'TAN',
    'TANH',
    'TRUNC',

    // navigation
    'FIRST_VALUE',
    'LAG',
    'LAST_VALUE',
    'LEAD',
    'NTH_VALUE',
    'PERCENTILE_CONT',
    'PERCENTILE_DISC',
    'RANK',
    'DENSE_RANK',
    'ROW_NUMBER',
    'CUME_DIST',
    'NTILE',
    'PERCENT_RANK',

    // geography
    'ST_AREA',
    'ST_ASBINARY',
    'ST_ASGEOJSON',
    'ST_ASTEXT',
    'ST_BOUNDARY',
    'ST_BUFFER',
    'ST_BUFFERWITHTOLERANCE',
    'ST_CENTROID',
    'ST_CENTROID_AGG',
    'ST_CLOSESTPOINT',
    'ST_CLUSTERDBSCAN',
    'ST_CONTAINS',
    'ST_CONVEXHULL',
    'ST_COVEREDBY',
    'ST_COVERS',
    'ST_DIFFERENCE',
    'ST_DIMENSION',
    'ST_DISJOINT',
    'ST_DISTANCE',
    'ST_DUMP',
    'ST_DWITHIN',
    'ST_ENDPOINT',
    'ST_EQUALS',
    'ST_EXTERIORRING',
    'ST_GEOGFROM',
    'ST_GEOGFROMGEOJSON',
    'ST_GEOGFROMTEXT',
    'ST_GEOGFROMWKB',
    'ST_GEOGPOINT',
    'ST_GEOGPOINTFROMGEOHASH',
    'ST_GEOHASH',
    'ST_GEOMETRYTYPE',
    'ST_INTERIORRINGS',
    'ST_INTERSECTION',
    'ST_INTERSECTS',
    'ST_INTERSECTSBOX',
    'ST_ISCOLLECTION',
    'ST_ISEMPTY',
    'ST_LENGTH',
    'ST_MAKELINE',
    'ST_MAKEPOLYGON',
    'ST_MAKEPOLYGONORIENTED',
    'ST_MAXDISTANCE',
    'ST_NPOINTS',
    'ST_NUMGEOMETRIES',
    'ST_NUMPOINTS',
    'ST_PERIMETER',
    'ST_POINTN',
    'ST_SIMPLIFY',
    'ST_SNAPTOGRID',
    'STARTPOINT',
    'ST_TOKML',
    'ST_TOUCHES',
    'ST_UNARYUNION',
    'ST_UNION',
    'ST_UNION_AGG',
    'ST_WITHIN',
    'ST_X',
    'ST_Y',
];

export const functionSignatures: FunctionSignature[] = [
    // --- AGGREGATE ---
    { name: 'ANY_VALUE', params: ['expression'], returnType: 'T', description: '返回分组中任意一行的值', category: 'aggregate' },
    { name: 'APPROX_COUNT_DISTINCT', params: ['expression'], returnType: 'int64', description: '返回近似不重复值的数量', category: 'aggregate' },
    { name: 'APPROX_QUANTILES', params: ['expression', 'number n'], returnType: 'array<float64>', description: '返回近似分位数数组', category: 'aggregate' },
    { name: 'APPROX_TOP_COUNT', params: ['expression', 'number n'], returnType: 'array<struct>', description: '返回近似出现次数最多的元素', category: 'aggregate' },
    { name: 'ARRAY_AGG', params: ['expression', 'ORDER BY sort_expression', 'LIMIT n'], returnType: 'array', description: '将值聚合为数组', category: 'aggregate' },
    { name: 'ARRAY_CONCAT_AGG', params: ['expression'], returnType: 'array', description: '将所有数组值连接成一个数组', category: 'aggregate' },
    { name: 'AVG', params: ['expression'], returnType: 'float64', description: '返回列的平均值', category: 'aggregate' },
    { name: 'BIT_AND', params: ['expression'], returnType: 'int64', description: '返回所有值的按位与运算结果', category: 'aggregate' },
    { name: 'BIT_OR', params: ['expression'], returnType: 'int64', description: '返回所有值的按位或运算结果', category: 'aggregate' },
    { name: 'BIT_XOR', params: ['expression'], returnType: 'int64', description: '返回所有值的按位异或运算结果', category: 'aggregate' },
    { name: 'COUNT', params: ['expression|*'], returnType: 'int64', description: '返回行数或非 NULL 行数', category: 'aggregate' },
    { name: 'COUNTIF', params: ['boolean_expression'], returnType: 'int64', description: '返回满足条件的行数', category: 'aggregate' },
    { name: 'MAX', params: ['expression'], returnType: 'T', description: '返回列的最大值', category: 'aggregate' },
    { name: 'MIN', params: ['expression'], returnType: 'T', description: '返回列的最小值', category: 'aggregate' },
    { name: 'STRING_AGG', params: ['expression', 'delimiter', 'ORDER BY sort_expression'], returnType: 'string', description: '将字符串聚合为分隔字符串', category: 'aggregate' },
    { name: 'SUM', params: ['expression'], returnType: 'T', description: '返回列的总和', category: 'aggregate' },
    { name: 'STDDEV_POP', params: ['expression'], returnType: 'float64', description: '返回总体标准差', category: 'aggregate' },
    { name: 'STDDEV_SAMP', params: ['expression'], returnType: 'float64', description: '返回样本标准差', category: 'aggregate' },

    // --- ARRAY ---
    { name: 'ARRAY', params: ['expression', '...'], returnType: 'array<T>', description: '创建 ARRAY 类型值', category: 'collection' },
    { name: 'ARRAY_CONCAT', params: ['array_expression', '...'], returnType: 'array', description: '连接多个数组', category: 'collection' },
    { name: 'ARRAY_LENGTH', params: ['array_expression'], returnType: 'int64', description: '返回数组长度', category: 'collection' },
    { name: 'ARRAY_REVERSE', params: ['array_expression'], returnType: 'array', description: '反转数组元素顺序', category: 'collection' },
    { name: 'ARRAY_TO_STRING', params: ['array_expression', 'delimiter', 'null_string'], returnType: 'string', description: '将数组元素连接为字符串', category: 'collection' },
    { name: 'GENERATE_ARRAY', params: ['start', 'end', 'step'], returnType: 'array<int64>', description: '生成等步长的整数数组', category: 'collection' },
    { name: 'GENERATE_DATE_ARRAY', params: ['start_date', 'end_date', 'INTERVAL step'], returnType: 'array<date>', description: '生成日期数组', category: 'date' },

    // --- DATE ---
    { name: 'CURRENT_DATE', params: [], returnType: 'date', description: '返回当前日期', category: 'date' },
    { name: 'CURRENT_DATETIME', params: [], returnType: 'datetime', description: '返回当前日期时间', category: 'date' },
    { name: 'CURRENT_TIME', params: [], returnType: 'time', description: '返回当前时间', category: 'date' },
    { name: 'CURRENT_TIMESTAMP', params: [], returnType: 'timestamp', description: '返回当前时间戳', category: 'date' },
    { name: 'DATE', params: ['expression'], returnType: 'date', description: '将表达式转换为 DATE 类型', category: 'date' },
    { name: 'DATE_ADD', params: ['date_expression', 'INTERVAL interval'], returnType: 'date', description: '为日期添加指定时间间隔', category: 'date' },
    { name: 'DATE_DIFF', params: ['date1', 'date2', 'date_part'], returnType: 'int64', description: '返回两个日期之间的差值', category: 'date' },
    { name: 'DATE_SUB', params: ['date_expression', 'INTERVAL interval'], returnType: 'date', description: '从日期减去指定时间间隔', category: 'date' },
    { name: 'DATE_TRUNC', params: ['date_expression', 'date_part'], returnType: 'date', description: '将日期截断到指定精度', category: 'date' },
    { name: 'DATETIME', params: ['expression'], returnType: 'datetime', description: '将表达式转换为 DATETIME 类型', category: 'date' },
    { name: 'DATETIME_TRUNC', params: ['datetime_expression', 'date_part'], returnType: 'datetime', description: '将日期时间截断到指定精度', category: 'date' },
    { name: 'EXTRACT', params: ['date_part', 'FROM date_expression'], returnType: 'int64', description: '从日期中提取指定部分', category: 'date' },
    { name: 'FORMAT_DATE', params: ['format_string', 'date_expression'], returnType: 'string', description: '按格式将日期转换为字符串', category: 'date' },
    { name: 'FORMAT_TIMESTAMP', params: ['format_string', 'timestamp'], returnType: 'string', description: '按格式将时间戳转换为字符串', category: 'date' },
    { name: 'LAST_DAY', params: ['date_expression', 'date_part'], returnType: 'date', description: '返回日期所在期间的最后一天', category: 'date' },
    { name: 'PARSE_DATE', params: ['format_string', 'date_string'], returnType: 'date', description: '按格式解析日期字符串', category: 'date' },
    { name: 'PARSE_DATETIME', params: ['format_string', 'datetime_string'], returnType: 'datetime', description: '按格式解析日期时间字符串', category: 'date' },
    { name: 'PARSE_TIMESTAMP', params: ['format_string', 'timestamp_string', 'timezone'], returnType: 'timestamp', description: '按格式解析时间戳字符串', category: 'date' },
    { name: 'TIMESTAMP', params: ['expression'], returnType: 'timestamp', description: '将表达式转换为 TIMESTAMP 类型', category: 'date' },
    { name: 'TIMESTAMP_DIFF', params: ['timestamp1', 'timestamp2', 'date_part'], returnType: 'int64', description: '返回两个时间戳之间的差值', category: 'date' },
    { name: 'UNIX_SECONDS', params: ['timestamp_expression'], returnType: 'int64', description: '返回时间戳对应的 Unix 秒数', category: 'date' },

    // --- STRING ---
    { name: 'ASCII', params: ['string_expression'], returnType: 'int64', description: '返回字符串第一个字符的 ASCII 码', category: 'string' },
    { name: 'BEGINS_WITH', params: ['str', 'substr'], returnType: 'boolean', description: '判断字符串是否以指定子串开头', category: 'string' },
    { name: 'CHAR_LENGTH', params: ['string_expression'], returnType: 'int64', description: '返回字符串的字符长度', category: 'string' },
    { name: 'CONCAT', params: ['str1', 'str2', '...'], returnType: 'string', description: '连接多个字符串', category: 'string' },
    { name: 'CONTAINS_SUBSTR', params: ['str', 'substr'], returnType: 'boolean', description: '判断字符串是否包含子串', category: 'string' },
    { name: 'ENDS_WITH', params: ['str', 'substr'], returnType: 'boolean', description: '判断字符串是否以指定子串结尾', category: 'string' },
    { name: 'FORMAT', params: ['format_string', '... values'], returnType: 'string', description: '返回格式化后的字符串', category: 'string' },
    { name: 'FROM_BASE64', params: ['base64_string'], returnType: 'bytes', description: '将 Base64 字符串解码为字节', category: 'string' },
    { name: 'INITCAP', params: ['string_expression'], returnType: 'string', description: '返回每个单词首字母大写的字符串', category: 'string' },
    { name: 'INSTR', params: ['source', 'search', 'position', 'occurrence'], returnType: 'int64', description: '返回子串在字符串中首次出现的位置', category: 'string' },
    { name: 'LEFT', params: ['string_expression', 'length'], returnType: 'string', description: '返回字符串左侧指定长度的子串', category: 'string' },
    { name: 'LENGTH', params: ['string_expression'], returnType: 'int64', description: '返回字符串的字符长度', category: 'string' },
    { name: 'LOWER', params: ['string_expression'], returnType: 'string', description: '返回全小写的字符串', category: 'string' },
    { name: 'LPAD', params: ['str', 'length', 'pad_str'], returnType: 'string', description: '在左侧填充字符至指定长度', category: 'string' },
    { name: 'LTRIM', params: ['string_expression', 'characters_to_trim'], returnType: 'string', description: '去除字符串左侧的指定字符', category: 'string' },
    { name: 'REGEXP_CONTAINS', params: ['str', 'regexp'], returnType: 'boolean', description: '判断字符串是否匹配正则表达式', category: 'string' },
    { name: 'REGEXP_EXTRACT', params: ['str', 'regexp', 'position', 'occurrence'], returnType: 'string', description: '提取匹配正则的子串', category: 'string' },
    { name: 'REGEXP_EXTRACT_ALL', params: ['str', 'regexp'], returnType: 'array<string>', description: '提取所有匹配正则的子串', category: 'string' },
    { name: 'REGEXP_REPLACE', params: ['str', 'regexp', 'replacement'], returnType: 'string', description: '替换匹配正则的子串', category: 'string' },
    { name: 'REPLACE', params: ['str', 'from_value', 'to_value'], returnType: 'string', description: '替换字符串中所有匹配的子串', category: 'string' },
    { name: 'REPEAT', params: ['str', 'count'], returnType: 'string', description: '重复字符串指定次数', category: 'string' },
    { name: 'REVERSE', params: ['string_expression'], returnType: 'string', description: '反转字符串', category: 'string' },
    { name: 'RIGHT', params: ['string_expression', 'length'], returnType: 'string', description: '返回字符串右侧指定长度的子串', category: 'string' },
    { name: 'RPAD', params: ['str', 'length', 'pad_str'], returnType: 'string', description: '在右侧填充字符至指定长度', category: 'string' },
    { name: 'RTRIM', params: ['string_expression', 'characters_to_trim'], returnType: 'string', description: '去除字符串右侧的指定字符', category: 'string' },
    { name: 'SPLIT', params: ['str', 'delimiter'], returnType: 'array<string>', description: '按分隔符拆分字符串', category: 'string' },
    { name: 'STARTS_WITH', params: ['str', 'substr'], returnType: 'boolean', description: '判断字符串是否以指定子串开头', category: 'string' },
    { name: 'SUBSTR', params: ['str', 'position', 'length'], returnType: 'string', description: '返回从指定位置开始的子串', category: 'string' },
    { name: 'SUBSTRING', params: ['str', 'position', 'length'], returnType: 'string', description: 'SUBSTR 的别名', category: 'string' },
    { name: 'TO_BASE64', params: ['bytes_expression'], returnType: 'string', description: '将字节编码为 Base64 字符串', category: 'string' },
    { name: 'TO_HEX', params: ['bytes_expression'], returnType: 'string', description: '将字节编码为十六进制字符串', category: 'string' },
    { name: 'TRANSLATE', params: ['str', 'from_characters', 'to_characters'], returnType: 'string', description: '将字符串中的字符一一替换', category: 'string' },
    { name: 'TRIM', params: ['str', 'characters_to_trim'], returnType: 'string', description: '去除字符串两侧的指定字符', category: 'string' },
    { name: 'UPPER', params: ['string_expression'], returnType: 'string', description: '返回全大写的字符串', category: 'string' },

    // --- CONVERSION ---
    { name: 'BOOL', params: ['expression'], returnType: 'bool', description: '将表达式转换为布尔类型', category: 'type-conversion' },
    { name: 'CAST', params: ['expression', 'AS typename'], returnType: 'typename', description: '将表达式转换为指定类型', category: 'type-conversion' },
    { name: 'SAFE_CAST', params: ['expression', 'AS typename'], returnType: 'typename', description: '安全类型转换，失败返回 NULL', category: 'type-conversion' },
    { name: 'STRING', params: ['expression'], returnType: 'string', description: '将表达式转换为字符串类型', category: 'type-conversion' },
    { name: 'TO_JSON', params: ['expression'], returnType: 'json', description: '将表达式转换为 JSON 类型', category: 'type-conversion' },
    { name: 'TO_JSON_STRING', params: ['expression'], returnType: 'string', description: '将表达式转换为 JSON 字符串', category: 'type-conversion' },

    // --- JSON ---
    { name: 'JSON_EXTRACT', params: ['json_expression', 'json_path'], returnType: 'json', description: '从 JSON 中提取指定路径的值', category: 'json' },
    { name: 'JSON_EXTRACT_SCALAR', params: ['json_expression', 'json_path'], returnType: 'string', description: '从 JSON 中提取标量值', category: 'json' },
    { name: 'JSON_QUERY', params: ['json_expression', 'json_path'], returnType: 'json', description: '从 JSON 中查询指定路径的数据', category: 'json' },
    { name: 'JSON_VALUE', params: ['json_expression', 'json_path'], returnType: 'string', description: '从 JSON 中提取并返回标量值', category: 'json' },
    { name: 'PARSE_JSON', params: ['json_string'], returnType: 'json', description: '将 JSON 字符串解析为 JSON 类型', category: 'json' },

    // --- MATH ---
    { name: 'ABS', params: ['numeric_expression'], returnType: 'numeric', description: '返回数值的绝对值', category: 'math' },
    { name: 'CEIL', params: ['numeric_expression'], returnType: 'numeric', description: '返回不小于参数的最小整数', category: 'math' },
    { name: 'CEILING', params: ['numeric_expression'], returnType: 'numeric', description: 'CEIL 的别名，向上取整', category: 'math' },
    { name: 'COS', params: ['numeric_expression'], returnType: 'float64', description: '返回余弦值', category: 'math' },
    { name: 'EXP', params: ['numeric_expression'], returnType: 'float64', description: '返回 e 的指定次幂', category: 'math' },
    { name: 'FLOOR', params: ['numeric_expression'], returnType: 'numeric', description: '返回不大于参数的最大整数', category: 'math' },
    { name: 'GREATEST', params: ['expr1', 'expr2', '...'], returnType: 'T', description: '返回所有参数中的最大值', category: 'math' },
    { name: 'IS_INF', params: ['numeric_expression'], returnType: 'boolean', description: '判断数值是否为无穷大', category: 'math' },
    { name: 'IS_NAN', params: ['numeric_expression'], returnType: 'boolean', description: '判断数值是否为 NaN', category: 'math' },
    { name: 'LEAST', params: ['expr1', 'expr2', '...'], returnType: 'T', description: '返回所有参数中的最小值', category: 'math' },
    { name: 'LN', params: ['numeric_expression'], returnType: 'float64', description: '返回自然对数', category: 'math' },
    { name: 'LOG', params: ['numeric_expression', 'base'], returnType: 'float64', description: '返回指定底数的对数', category: 'math' },
    { name: 'LOG10', params: ['numeric_expression'], returnType: 'float64', description: '返回以 10 为底的对数', category: 'math' },
    { name: 'MOD', params: ['dividend', 'divisor'], returnType: 'numeric', description: '返回除法运算的余数', category: 'math' },
    { name: 'PI', params: [], returnType: 'float64', description: '返回圆周率', category: 'math' },
    { name: 'POW', params: ['base', 'exponent'], returnType: 'float64', description: '返回 base 的 exponent 次幂', category: 'math' },
    { name: 'POWER', params: ['base', 'exponent'], returnType: 'float64', description: 'POW 的别名', category: 'math' },
    { name: 'RADIANS', params: ['numeric_expression'], returnType: 'float64', description: '将角度转换为弧度', category: 'math' },
    { name: 'RAND', params: [], returnType: 'float64', description: '返回 [0, 1) 之间的随机数', category: 'math' },
    { name: 'ROUND', params: ['numeric_expression', 'digits'], returnType: 'numeric', description: '四舍五入到指定位数', category: 'math' },
    { name: 'SAFE_ADD', params: ['x', 'y'], returnType: 'numeric', description: '安全加法，溢出返回 NULL', category: 'math' },
    { name: 'SAFE_DIVIDE', params: ['x', 'y'], returnType: 'float64', description: '安全除法，除零返回 NULL', category: 'math' },
    { name: 'SAFE_MULTIPLY', params: ['x', 'y'], returnType: 'numeric', description: '安全乘法，溢出返回 NULL', category: 'math' },
    { name: 'SAFE_SUBTRACT', params: ['x', 'y'], returnType: 'numeric', description: '安全减法，溢出返回 NULL', category: 'math' },
    { name: 'SIGN', params: ['numeric_expression'], returnType: 'numeric', description: '返回数值的符号（1/0/-1）', category: 'math' },
    { name: 'SIN', params: ['numeric_expression'], returnType: 'float64', description: '返回正弦值', category: 'math' },
    { name: 'SQRT', params: ['numeric_expression'], returnType: 'float64', description: '返回平方根', category: 'math' },
    { name: 'TAN', params: ['numeric_expression'], returnType: 'float64', description: '返回正切值', category: 'math' },
    { name: 'TRUNC', params: ['numeric_expression', 'digits'], returnType: 'numeric', description: '截断到指定位数', category: 'math' },

    // --- NAVIGATION ---
    { name: 'FIRST_VALUE', params: ['expression'], returnType: 'T', description: '返回窗口内第一行的值', category: 'window' },
    { name: 'LAG', params: ['expression', 'offset', 'default_value'], returnType: 'T', description: '返回当前行之前 offset 行的值', category: 'window' },
    { name: 'LAST_VALUE', params: ['expression'], returnType: 'T', description: '返回窗口内最后一行的值', category: 'window' },
    { name: 'LEAD', params: ['expression', 'offset', 'default_value'], returnType: 'T', description: '返回当前行之后 offset 行的值', category: 'window' },
    { name: 'NTH_VALUE', params: ['expression', 'n'], returnType: 'T', description: '返回窗口内第 n 行的值', category: 'window' },
    { name: 'RANK', params: [], returnType: 'int64', description: '返回排序名次（有间隔）', category: 'window' },
    { name: 'DENSE_RANK', params: [], returnType: 'int64', description: '返回排序名次（无间隔）', category: 'window' },
    { name: 'ROW_NUMBER', params: [], returnType: 'int64', description: '返回行号（从 1 开始，无重复）', category: 'window' },
    { name: 'CUME_DIST', params: [], returnType: 'float64', description: '返回累积分布值（0-1）', category: 'window' },
    { name: 'NTILE', params: ['n'], returnType: 'int64', description: '将行分配到 n 个桶中', category: 'window' },
    { name: 'PERCENT_RANK', params: [], returnType: 'float64', description: '返回相对排名百分比（0-1）', category: 'window' },

    // --- STRUCT ---
    { name: 'STRUCT', params: ['field AS name', '...'], returnType: 'struct', description: '创建 STRUCT 类型值', category: 'collection' },

    // --- TABLE ---
    { name: 'UNNEST', params: ['array_expression'], returnType: 'temporary table', description: '将数组展开为多行', category: 'table' },
];