export const AstNodeType = {
    SELECT: 'select',
    INSERT: 'insert',
    REPLACE: 'replace',
    UPDATE: 'update',
    DELETE: 'delete',
    CREATE: 'create',
    ALTER: 'alter',
    DROP: 'drop',
    USE: 'use',
    COLUMN_REF: 'column_ref',
    BINARY_EXPR: 'binary_expr',
    FUNCTION: 'function',
    AGGR_FUNC: 'aggr_func',
    EXPR_LIST: 'expr_list',
    CASE: 'case',
    CAST: 'cast',
    INTERVAL: 'interval',
    PARAM: 'param',
    UNARY_EXPR: 'unary_expr',
    TERNARY_EXPR: 'ternary_expr',
    STRING: 'string',
    SINGLE_QUOTE_STRING: 'single_quote_string',
    DOUBLE_QUOTE_STRING: 'double_quote_string',
    NUMBER: 'number',
    BIGINT: 'bigint',
    BOOLEAN: 'boolean',
    NULL: 'null',
    STAR: 'star',
    ORIGIN: 'origin',
    DEFAULT: 'default',
    DUAL: 'dual',
    UNION: 'union',
} as const

export type AstNodeTypeValue = (typeof AstNodeType)[keyof typeof AstNodeType]