        let currentConfig = {
            enableSmartCommentToggle: true,
            headerAuthor: '',
            headerModifier: '',
            completionCommentSnippets: true,
        };
        
        const presets = {
            default: {
                dialect: 'hive',
                keywordCase: 'preserve',
                dataTypeCase: 'preserve',
                functionCase: 'preserve',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'before',
                expressionWidth: 50,
                linesBetweenQueries: 1,
                denseOperators: false,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: false,
                newlineAfterSelect: true,
                newlineAfterFrom: true,
                newlineBeforeWhere: true,
                newlineAfterWhere: true,
                newlineBeforeOrderBy: true,
                newlineBeforeGroupBy: true,
                newlineBeforeHaving: true,
                newlineBeforeLimit: true,
            newlineAfterGroupBy: true,
            newlineAfterHaving: true,
            newlineAfterOrderBy: true,
            newlineAfterLimit: false,
            newlineAfterJoin: true,
            newlineBeforeOn: true,
            newlineBeforeSetOperation: true,
            newlineAfterCase: true,
            newlineAfterWhen: true,
            newlineAfterThen: false,
            newlineAfterElse: false,
            newlineAfterIn: false,
                maxLineLength: 120,
                tabulateAlias: false,
                reservedKeywordCase: 'preserve',
                builtinFunctionCase: 'preserve',
                newlineBeforeJoin: true,
                newlineAfterComma: true,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: true,
                breakAfterFromItem: true,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 80,
            nullCase: 'preserve',
            booleanCase: 'preserve',
            indentJoinConditions: true,
            indentWhen: true,
            indentThen: true,
            indentCteBody: true,
            alignOnClauses: false,
            alignInsertColumns: false,
            alignInsertValuesGroups: false,
            maxItemsInlineList: 5,
            cteCommaPosition: 'before',
            subqueryParenStyle: 'inline',
            commentPosition: 'preserve',
            blankLinesBeforeSetOperation: 1,
            blankLinesAfterSetOperation: 0,
            newlineBeforeLateralView: true,
            newlineBeforeDistributeBy: true,
            newlineBeforeClusterBy: true,
            newlineBeforeSortBy: true,
                ignoreTabSettings: false,
                tabSizeOverride: 2,
                insertSpacesOverride: true,
                enableEnhancedChecks: true,
                enableLinter: true,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: true,
                enableOutlineView: true,
                enableStatusBar: true,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: true,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: true,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: true,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: true,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: true,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: true,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: true,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: true,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: false,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            },
            hive: {
                dialect: 'hive',
                keywordCase: 'upper',
                dataTypeCase: 'upper',
                functionCase: 'lower',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'before',
                expressionWidth: 60,
                linesBetweenQueries: 2,
                denseOperators: false,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: true,
                newlineAfterSelect: true,
                newlineAfterFrom: true,
                newlineBeforeWhere: true,
                newlineAfterWhere: true,
                newlineBeforeOrderBy: true,
                newlineBeforeGroupBy: true,
                newlineBeforeHaving: true,
                newlineBeforeLimit: true,
                newlineAfterGroupBy: true,
                newlineAfterHaving: true,
                newlineAfterOrderBy: true,
                newlineAfterLimit: false,
                newlineAfterJoin: true,
                newlineBeforeOn: true,
                newlineBeforeSetOperation: true,
                newlineAfterCase: true,
                newlineAfterWhen: true,
                newlineAfterThen: false,
                newlineAfterElse: false,
                newlineAfterIn: false,
                maxLineLength: 100,
                tabulateAlias: true,
                reservedKeywordCase: 'upper',
                builtinFunctionCase: 'lower',
                newlineBeforeJoin: true,
                newlineAfterComma: true,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: true,
                breakAfterFromItem: true,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 80,
                nullCase: 'preserve',
                booleanCase: 'preserve',
                indentJoinConditions: true,
                indentWhen: true,
                indentThen: true,
                indentCteBody: true,
                alignOnClauses: false,
                alignInsertColumns: false,
                alignInsertValuesGroups: false,
                maxItemsInlineList: 5,
                cteCommaPosition: 'before',
                subqueryParenStyle: 'inline',
                commentPosition: 'preserve',
                blankLinesBeforeSetOperation: 1,
                blankLinesAfterSetOperation: 0,
                newlineBeforeLateralView: true,
                newlineBeforeDistributeBy: true,
                newlineBeforeClusterBy: true,
                newlineBeforeSortBy: true,
                ignoreTabSettings: false,
                tabSizeOverride: 2,
                insertSpacesOverride: true,
                enableEnhancedChecks: true,
                enableLinter: true,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: true,
                enableOutlineView: true,
                enableStatusBar: true,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: true,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: true,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: true,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: true,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: true,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: true,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: true,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: true,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: true,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            },
            mysql: {
                dialect: 'mysql',
                keywordCase: 'upper',
                dataTypeCase: 'upper',
                functionCase: 'preserve',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'after',
                expressionWidth: 50,
                linesBetweenQueries: 1,
                denseOperators: false,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: false,
                newlineAfterSelect: true,
                newlineAfterFrom: true,
                newlineBeforeWhere: true,
                newlineAfterWhere: true,
                newlineBeforeOrderBy: true,
                newlineBeforeGroupBy: true,
                newlineBeforeHaving: true,
                newlineBeforeLimit: true,
                newlineAfterGroupBy: true,
                newlineAfterHaving: true,
                newlineAfterOrderBy: true,
                newlineAfterLimit: false,
                newlineAfterJoin: true,
                newlineBeforeOn: true,
                newlineBeforeSetOperation: true,
                newlineAfterCase: true,
                newlineAfterWhen: true,
                newlineAfterThen: false,
                newlineAfterElse: false,
                newlineAfterIn: false,
                maxLineLength: 120,
                tabulateAlias: false,
                reservedKeywordCase: 'upper',
                builtinFunctionCase: 'preserve',
                newlineBeforeJoin: true,
                newlineAfterComma: true,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: true,
                breakAfterFromItem: true,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 80,
                nullCase: 'preserve',
                booleanCase: 'preserve',
                indentJoinConditions: true,
                indentWhen: true,
                indentThen: true,
                indentCteBody: true,
                alignOnClauses: false,
                alignInsertColumns: false,
                alignInsertValuesGroups: false,
                maxItemsInlineList: 5,
                cteCommaPosition: 'before',
                subqueryParenStyle: 'inline',
                commentPosition: 'preserve',
                blankLinesBeforeSetOperation: 1,
                blankLinesAfterSetOperation: 0,
                newlineBeforeLateralView: true,
                newlineBeforeDistributeBy: true,
                newlineBeforeClusterBy: true,
                newlineBeforeSortBy: true,
                ignoreTabSettings: false,
                tabSizeOverride: 4,
                insertSpacesOverride: true,
                enableEnhancedChecks: true,
                enableLinter: true,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: true,
                enableOutlineView: true,
                enableStatusBar: true,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: true,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: true,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: true,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: true,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: true,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: true,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: true,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: true,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: true,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            },
            compact: {
                dialect: 'hive',
                keywordCase: 'preserve',
                dataTypeCase: 'preserve',
                functionCase: 'preserve',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'before',
                expressionWidth: 80,
                linesBetweenQueries: 0,
                denseOperators: true,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: false,
                newlineAfterSelect: false,
                newlineAfterFrom: false,
                newlineBeforeWhere: false,
                newlineAfterWhere: false,
                newlineBeforeOrderBy: false,
                newlineBeforeGroupBy: false,
                newlineBeforeHaving: false,
                newlineBeforeLimit: false,
                newlineAfterGroupBy: false,
                newlineAfterHaving: false,
                newlineAfterOrderBy: false,
                newlineAfterLimit: false,
                newlineAfterJoin: false,
                newlineBeforeOn: false,
                newlineBeforeSetOperation: false,
                newlineAfterCase: false,
                newlineAfterWhen: false,
                newlineAfterThen: false,
                newlineAfterElse: false,
                newlineAfterIn: false,
                maxLineLength: 150,
                tabulateAlias: false,
                reservedKeywordCase: 'preserve',
                builtinFunctionCase: 'preserve',
                newlineBeforeJoin: false,
                newlineAfterComma: false,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: false,
                breakAfterFromItem: false,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 100,
                nullCase: 'preserve',
                booleanCase: 'preserve',
                indentJoinConditions: false,
                indentWhen: false,
                indentThen: false,
                indentCteBody: false,
                alignOnClauses: false,
                alignInsertColumns: false,
                alignInsertValuesGroups: false,
                maxItemsInlineList: 10,
                cteCommaPosition: 'before',
                subqueryParenStyle: 'inline',
                commentPosition: 'preserve',
                blankLinesBeforeSetOperation: 0,
                blankLinesAfterSetOperation: 0,
                newlineBeforeLateralView: false,
                newlineBeforeDistributeBy: false,
                newlineBeforeClusterBy: false,
                newlineBeforeSortBy: false,
                ignoreTabSettings: false,
                tabSizeOverride: 2,
                insertSpacesOverride: true,
                enableEnhancedChecks: false,
                enableLinter: false,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: false,
                enableOutlineView: false,
                enableStatusBar: false,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: false,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: false,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: false,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: false,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: false,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: false,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: false,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: false,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: false,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            },
            postgresql: {
                dialect: 'postgresql',
                keywordCase: 'upper',
                dataTypeCase: 'lower',
                functionCase: 'lower',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'before',
                expressionWidth: 50,
                linesBetweenQueries: 1,
                denseOperators: false,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: false,
                newlineAfterSelect: true,
                newlineAfterFrom: true,
                newlineBeforeWhere: true,
                newlineAfterWhere: true,
                newlineBeforeOrderBy: true,
                newlineBeforeGroupBy: true,
                newlineBeforeHaving: true,
                newlineBeforeLimit: true,
                maxLineLength: 120,
                tabulateAlias: false,
                reservedKeywordCase: 'upper',
                builtinFunctionCase: 'lower',
                newlineBeforeJoin: true,
                newlineAfterComma: true,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: true,
                breakAfterFromItem: true,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 80,
                ignoreTabSettings: false,
                tabSizeOverride: 2,
                insertSpacesOverride: true,
                enableEnhancedChecks: true,
                enableLinter: true,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: true,
                enableOutlineView: true,
                enableStatusBar: true,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: true,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: true,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: true,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: true,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: true,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: true,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: true,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: true,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: true,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            },
            bigquery: {
                dialect: 'bigquery',
                keywordCase: 'upper',
                dataTypeCase: 'upper',
                functionCase: 'lower',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'before',
                expressionWidth: 50,
                linesBetweenQueries: 1,
                denseOperators: false,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: false,
                newlineAfterSelect: true,
                newlineAfterFrom: true,
                newlineBeforeWhere: true,
                newlineAfterWhere: true,
                newlineBeforeOrderBy: true,
                newlineBeforeGroupBy: true,
                newlineBeforeHaving: true,
                newlineBeforeLimit: true,
                maxLineLength: 120,
                tabulateAlias: false,
                reservedKeywordCase: 'upper',
                builtinFunctionCase: 'lower',
                newlineBeforeJoin: true,
                newlineAfterComma: true,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: true,
                breakAfterFromItem: true,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 80,
                ignoreTabSettings: false,
                tabSizeOverride: 2,
                insertSpacesOverride: true,
                enableEnhancedChecks: true,
                enableLinter: true,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: true,
                enableOutlineView: true,
                enableStatusBar: true,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: true,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: true,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: true,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: true,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: true,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: true,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: true,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: true,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: true,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            },
            sqlite: {
                dialect: 'sqlite',
                keywordCase: 'upper',
                dataTypeCase: 'upper',
                functionCase: 'lower',
                identifierCase: 'preserve',
                indentStyle: 'standard',
                logicalOperatorNewline: 'before',
                expressionWidth: 50,
                linesBetweenQueries: 1,
                denseOperators: false,
                newlineBeforeSemicolon: false,
                commaPosition: 'after',
                alignColumnDefinitions: false,
                newlineAfterSelect: true,
                newlineAfterFrom: true,
                newlineBeforeWhere: true,
                newlineAfterWhere: true,
                newlineBeforeOrderBy: true,
                newlineBeforeGroupBy: true,
                newlineBeforeHaving: true,
                newlineBeforeLimit: true,
                maxLineLength: 120,
                tabulateAlias: false,
                reservedKeywordCase: 'upper',
                builtinFunctionCase: 'lower',
                newlineBeforeJoin: true,
                newlineAfterComma: true,
                alignWhereClauses: false,
                alignCaseStatements: false,
                breakAfterSelectItem: true,
                breakAfterFromItem: true,
                spaceBeforeComma: false,
                spaceInsideParentheses: false,
                trimTrailingSpaces: true,
                semicolonAtEnd: true,
                singleLineMaxLength: 80,
                ignoreTabSettings: false,
                tabSizeOverride: 2,
                insertSpacesOverride: true,
                enableEnhancedChecks: true,
                enableLinter: true,
                showErrorLevel: true,
                showWarningLevel: true,
                showInfoLevel: true,
                enableCodeFolding: true,
                enableOutlineView: true,
                enableStatusBar: true,
                enableParameterHighlight: true,
                enableSnippets: true,
                enableQuickFix: true,
                enableSmartCommentToggle: true,
                headerAuthor: '',
                headerModifier: '',
                completionCommentSnippets: true,
                lintAvoidSelectStarEnabled: true,
                lintAvoidSelectStarSeverity: 'warning',
                lintExplicitJoinTypeEnabled: true,
                lintExplicitJoinTypeSeverity: 'information',
                lintLimitWithOrderByEnabled: true,
                lintLimitWithOrderBySeverity: 'warning',
                lintAvoidColumnCountMismatchEnabled: true,
                lintAvoidColumnCountMismatchSeverity: 'error',
                lintMissingPrimaryKeyEnabled: true,
                lintMissingPrimaryKeySeverity: 'warning',
                lintUseCurrentTimestampEnabled: true,
                lintUseCurrentTimestampSeverity: 'information',
                lintAvoidSelectInInsertEnabled: true,
                lintAvoidSelectInInsertSeverity: 'warning',
                lintDuplicateColumnAliasesEnabled: true,
                lintDuplicateColumnAliasesSeverity: 'warning',
                lintUppercaseKeywordsEnabled: true,
                lintUppercaseKeywordsSeverity: 'information',
                lintConsistentAliasingEnabled: false,
                lintConsistentAliasingSeverity: 'information',
                lintUseCoalesceOverIsnullEnabled: false,
                lintUseCoalesceOverIsnullSeverity: 'information',
                lintExplicitColumnAliasingEnabled: false,
                lintExplicitColumnAliasingSeverity: 'information',
                lintAvoidCorrelatedSubqueriesEnabled: false,
                lintAvoidCorrelatedSubqueriesSeverity: 'warning',
                lintLongQueryLineEnabled: false,
                lintLongQueryLineSeverity: 'information',
                lintMissingQueryCommentEnabled: false,
                lintMissingQueryCommentSeverity: 'warning',
                lintMissingColumnCommentEnabled: false,
                lintMissingColumnCommentSeverity: 'warning',
                lintCommentedOutCodeEnabled: false,
                lintCommentedOutCodeSeverity: 'information',
                lintExpiredTodoEnabled: false,
                lintExpiredTodoSeverity: 'warning'
            }
        };
        
        window.addEventListener('message', (event) => {
            const message = event.data;
            switch (message.command) {
                case 'loadConfig':
                    loadConfig(message.data);
                    break;
                case 'previewResult':
                    showPreviewResult(message.data);
                    break;
                case 'saveResult':
                    if (message.success) {
                        showToast('配置已保存', 'success');
                    } else {
                        showToast('保存失败，请重试', 'error');
                    }
                    break;
            }
        });
        
        function loadConfig(config) {
            currentConfig = { ...config };
            Object.keys(config).forEach(key => {
                const el = document.getElementById(key);
                if (el) {
                    if (el.type === 'checkbox') {
                        el.checked = config[key];
                    } else if (el.type === 'number') {
                        el.value = config[key];
                    } else {
                        el.value = config[key];
                    }
                }
            });
            updateTabOverrideGroup();
        }
        
        function collectConfig() {
            return {
                dialect: document.getElementById('dialect').value,
                keywordCase: document.getElementById('keywordCase').value,
                dataTypeCase: document.getElementById('dataTypeCase').value,
                functionCase: document.getElementById('functionCase').value,
                identifierCase: document.getElementById('identifierCase').value,
                indentStyle: document.getElementById('indentStyle').value,
                logicalOperatorNewline: document.getElementById('logicalOperatorNewline').value,
                expressionWidth: parseInt(document.getElementById('expressionWidth').value),
                linesBetweenQueries: parseInt(document.getElementById('linesBetweenQueries').value),
                denseOperators: document.getElementById('denseOperators').checked,
                newlineBeforeSemicolon: document.getElementById('newlineBeforeSemicolon').checked,
                commaPosition: document.getElementById('commaPosition').value,
                alignColumnDefinitions: document.getElementById('alignColumnDefinitions').checked,
                newlineAfterSelect: document.getElementById('newlineAfterSelect').checked,
                newlineAfterFrom: document.getElementById('newlineAfterFrom').checked,
                newlineBeforeWhere: document.getElementById('newlineBeforeWhere').checked,
                newlineAfterWhere: document.getElementById('newlineAfterWhere').checked,
                newlineBeforeOrderBy: document.getElementById('newlineBeforeOrderBy').checked,
                newlineBeforeGroupBy: document.getElementById('newlineBeforeGroupBy').checked,
                newlineBeforeHaving: document.getElementById('newlineBeforeHaving').checked,
                newlineBeforeLimit: document.getElementById('newlineBeforeLimit').checked,
                newlineAfterGroupBy: document.getElementById('newlineAfterGroupBy').checked,
                newlineAfterHaving: document.getElementById('newlineAfterHaving').checked,
                newlineAfterOrderBy: document.getElementById('newlineAfterOrderBy').checked,
                newlineAfterLimit: document.getElementById('newlineAfterLimit').checked,
                newlineAfterJoin: document.getElementById('newlineAfterJoin').checked,
                newlineBeforeOn: document.getElementById('newlineBeforeOn').checked,
                newlineBeforeSetOperation: document.getElementById('newlineBeforeSetOperation').checked,
                newlineAfterCase: document.getElementById('newlineAfterCase').checked,
                newlineAfterWhen: document.getElementById('newlineAfterWhen').checked,
                newlineAfterThen: document.getElementById('newlineAfterThen').checked,
                newlineAfterElse: document.getElementById('newlineAfterElse').checked,
                newlineAfterIn: document.getElementById('newlineAfterIn').checked,
                maxLineLength: parseInt(document.getElementById('maxLineLength').value),
                tabulateAlias: document.getElementById('tabulateAlias').checked,
                reservedKeywordCase: document.getElementById('reservedKeywordCase').value,
                builtinFunctionCase: document.getElementById('builtinFunctionCase').value,
                newlineBeforeJoin: document.getElementById('newlineBeforeJoin').checked,
                newlineAfterComma: document.getElementById('newlineAfterComma').checked,
                alignWhereClauses: document.getElementById('alignWhereClauses').checked,
                alignCaseStatements: document.getElementById('alignCaseStatements').checked,
                breakAfterSelectItem: document.getElementById('breakAfterSelectItem').checked,
                breakAfterFromItem: document.getElementById('breakAfterFromItem').checked,
                spaceBeforeComma: document.getElementById('spaceBeforeComma').checked,
                spaceInsideParentheses: document.getElementById('spaceInsideParentheses').checked,
                trimTrailingSpaces: document.getElementById('trimTrailingSpaces').checked,
                semicolonAtEnd: document.getElementById('semicolonAtEnd').checked,
                singleLineMaxLength: parseInt(document.getElementById('singleLineMaxLength').value),
                nullCase: document.getElementById('nullCase').value,
                booleanCase: document.getElementById('booleanCase').value,
                indentJoinConditions: document.getElementById('indentJoinConditions').checked,
                indentWhen: document.getElementById('indentWhen').checked,
                indentThen: document.getElementById('indentThen').checked,
                indentCteBody: document.getElementById('indentCteBody').checked,
                alignOnClauses: document.getElementById('alignOnClauses').checked,
                alignInsertColumns: document.getElementById('alignInsertColumns').checked,
                alignInsertValuesGroups: document.getElementById('alignInsertValuesGroups').checked,
                maxItemsInlineList: parseInt(document.getElementById('maxItemsInlineList').value),
                cteCommaPosition: document.getElementById('cteCommaPosition').value,
                subqueryParenStyle: document.getElementById('subqueryParenStyle').value,
                commentPosition: document.getElementById('commentPosition').value,
                blankLinesBeforeSetOperation: parseInt(document.getElementById('blankLinesBeforeSetOperation').value),
                blankLinesAfterSetOperation: parseInt(document.getElementById('blankLinesAfterSetOperation').value),
                newlineBeforeLateralView: document.getElementById('newlineBeforeLateralView').checked,
                newlineBeforeDistributeBy: document.getElementById('newlineBeforeDistributeBy').checked,
                newlineBeforeClusterBy: document.getElementById('newlineBeforeClusterBy').checked,
                newlineBeforeSortBy: document.getElementById('newlineBeforeSortBy').checked,
                ignoreTabSettings: document.getElementById('ignoreTabSettings').checked,
                tabSizeOverride: parseInt(document.getElementById('tabSizeOverride').value),
                insertSpacesOverride: true,
                enableEnhancedChecks: document.getElementById('enableEnhancedChecks').checked,
                enableLinter: document.getElementById('enableLinter').checked,
                showErrorLevel: document.getElementById('showErrorLevel').checked,
                showWarningLevel: document.getElementById('showWarningLevel').checked,
                showInfoLevel: document.getElementById('showInfoLevel').checked,
                enableCodeFolding: document.getElementById('enableCodeFolding').checked,
                enableOutlineView: document.getElementById('enableOutlineView').checked,
                enableStatusBar: document.getElementById('enableStatusBar').checked,
                enableParameterHighlight: document.getElementById('enableParameterHighlight').checked,
                enableSnippets: document.getElementById('enableSnippets').checked,
                enableQuickFix: document.getElementById('enableQuickFix').checked,
                enableSmartCommentToggle: document.getElementById('enableSmartCommentToggle').checked,
                headerAuthor: document.getElementById('headerAuthor').value,
                headerModifier: document.getElementById('headerModifier').value,
                completionCommentSnippets: document.getElementById('completionCommentSnippets').checked,
                lintAvoidSelectStarEnabled: document.getElementById('avoidSelectStarEnabled').checked,
                lintAvoidSelectStarSeverity: document.getElementById('avoidSelectStarSeverity').value,
                lintExplicitJoinTypeEnabled: document.getElementById('explicitJoinTypeEnabled').checked,
                lintExplicitJoinTypeSeverity: document.getElementById('explicitJoinTypeSeverity').value,
                lintLimitWithOrderByEnabled: document.getElementById('limitWithOrderByEnabled').checked,
                lintLimitWithOrderBySeverity: document.getElementById('limitWithOrderBySeverity').value,
                lintAvoidColumnCountMismatchEnabled: document.getElementById('avoidColumnCountMismatchEnabled').checked,
                lintAvoidColumnCountMismatchSeverity: document.getElementById('avoidColumnCountMismatchSeverity').value,
                lintMissingPrimaryKeyEnabled: document.getElementById('missingPrimaryKeyEnabled').checked,
                lintMissingPrimaryKeySeverity: document.getElementById('missingPrimaryKeySeverity').value,
                lintUseCurrentTimestampEnabled: document.getElementById('useCurrentTimestampEnabled').checked,
                lintUseCurrentTimestampSeverity: document.getElementById('useCurrentTimestampSeverity').value,
                lintAvoidSelectInInsertEnabled: document.getElementById('avoidSelectInInsertEnabled').checked,
                lintAvoidSelectInInsertSeverity: document.getElementById('avoidSelectInInsertSeverity').value,
                lintDuplicateColumnAliasesEnabled: document.getElementById('duplicateColumnAliasesEnabled').checked,
                lintDuplicateColumnAliasesSeverity: document.getElementById('duplicateColumnAliasesSeverity').value,
                lintUppercaseKeywordsEnabled: document.getElementById('uppercaseKeywordsEnabled').checked,
                lintUppercaseKeywordsSeverity: document.getElementById('uppercaseKeywordsSeverity').value,
                lintConsistentAliasingEnabled: document.getElementById('consistentAliasingEnabled').checked,
                lintConsistentAliasingSeverity: document.getElementById('consistentAliasingSeverity').value,
                lintUseCoalesceOverIsnullEnabled: document.getElementById('useCoalesceOverIsnullEnabled').checked,
                lintUseCoalesceOverIsnullSeverity: document.getElementById('useCoalesceOverIsnullSeverity').value,
                lintExplicitColumnAliasingEnabled: document.getElementById('explicitColumnAliasingEnabled').checked,
                lintExplicitColumnAliasingSeverity: document.getElementById('explicitColumnAliasingSeverity').value,
                lintAvoidCorrelatedSubqueriesEnabled: document.getElementById('avoidCorrelatedSubqueriesEnabled').checked,
                lintAvoidCorrelatedSubqueriesSeverity: document.getElementById('avoidCorrelatedSubqueriesSeverity').value,
                lintLongQueryLineEnabled: document.getElementById('longQueryLineEnabled').checked,
                lintLongQueryLineSeverity: document.getElementById('longQueryLineSeverity').value,
                lintMissingQueryCommentEnabled: document.getElementById('missingQueryCommentEnabled').checked,
                lintMissingQueryCommentSeverity: document.getElementById('missingQueryCommentSeverity').value,
                lintMissingColumnCommentEnabled: document.getElementById('missingColumnCommentEnabled').checked,
                lintMissingColumnCommentSeverity: document.getElementById('missingColumnCommentSeverity').value,
                lintCommentedOutCodeEnabled: document.getElementById('commentedOutCodeEnabled').checked,
                lintCommentedOutCodeSeverity: document.getElementById('commentedOutCodeSeverity').value,
                lintExpiredTodoEnabled: document.getElementById('expiredTodoEnabled').checked,
                lintExpiredTodoSeverity: document.getElementById('expiredTodoSeverity').value
            };
        }
        
        function saveConfig() {
            const config = collectConfig();
            vscode.postMessage({ command: 'updateConfig', data: config });
        }
        
        function showToast(message, type) {
            const toast = document.getElementById('toast');
            toast.textContent = message;
            toast.className = 'toast ' + type + ' show';
            setTimeout(() => { toast.classList.remove('show'); }, 2000);
        }
        
        function toggleGroup(header) {
            const arrow = header.querySelector('.cg-arrow');
            const body = header.nextElementSibling;
            const isOpen = body.classList.contains('open');
            if (isOpen) {
                arrow.classList.remove('open');
                body.classList.remove('open');
            } else {
                arrow.classList.add('open');
                body.classList.add('open');
            }
        }
        
        function resetConfig() {
            applyPreset('default');
            saveConfig();
        }
        
        function applyPreset(presetName) {
            const preset = presets[presetName];
            loadConfig(preset);
        }
        
        function previewFormat() {
            const sql = document.getElementById('previewInput').value;
            const config = collectConfig();
            vscode.postMessage({ command: 'previewFormat', sql, config });
        }
        
        function showPreviewResult(result) {
            const resultEl = document.getElementById('previewResult');
            resultEl.classList.remove('empty');
            resultEl.classList.add('success');
            resultEl.textContent = result;
            setTimeout(() => { resultEl.classList.remove('success'); }, 1000);
        }
        
        function updateTabOverrideGroup() {
            const group = document.getElementById('tabOverrideGroup');
            const checkbox = document.getElementById('ignoreTabSettings');
            group.style.display = checkbox.checked ? 'block' : 'none';
        }
        
        document.getElementById('ignoreTabSettings').addEventListener('change', updateTabOverrideGroup);

        const resizeHandle = document.getElementById('resizeHandle');
        const previewBody = document.querySelector('.preview-body');
        let isResizing = false;
        let startY = 0;
        let startHeight = 0;

        resizeHandle.addEventListener('mousedown', (e) => {
            isResizing = true;
            startY = e.clientY;
            startHeight = previewBody.offsetHeight;
            document.body.style.cursor = 'ns-resize';
            document.body.style.userSelect = 'none';
            e.preventDefault();
        });

        document.addEventListener('mousemove', (e) => {
            if (!isResizing) return;
            const delta = e.clientY - startY;
            const newHeight = Math.max(160, Math.min(600, startHeight + delta));
            previewBody.style.maxHeight = newHeight + 'px';
            previewBody.style.minHeight = newHeight + 'px';
        });

        document.addEventListener('mouseup', () => {
            if (isResizing) {
                isResizing = false;
                document.body.style.cursor = '';
                document.body.style.userSelect = '';
            }
        });

        const vscode = acquireVsCodeApi();
        vscode.postMessage({ command: 'getCurrentConfig' });
