import type { FunctionSignature } from '../../completion'

export const functions: string[] = [
    // https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF
    // math
    'ABS',
    'ACOS',
    'ASIN',
    'ATAN',
    'BIN',
    'BROUND',
    'CBRT',
    'CEIL',
    'CEILING',
    'CONV',
    'COS',
    'DEGREES',
    // 'E',
    'EXP',
    'FACTORIAL',
    'FLOOR',
    'GREATEST',
    'HEX',
    'LEAST',
    'LN',
    'LOG',
    'LOG10',
    'LOG2',
    'NEGATIVE',
    'PI',
    'PMOD',
    'POSITIVE',
    'POW',
    'POWER',
    'RADIANS',
    'RAND',
    'ROUND',
    'SHIFTLEFT',
    'SHIFTRIGHT',
    'SHIFTRIGHTUNSIGNED',
    'SIGN',
    'SIN',
    'SQRT',
    'TAN',
    'UNHEX',
    'WIDTH_BUCKET',

    // array
    'ARRAY_CONTAINS',
    'MAP_KEYS',
    'MAP_VALUES',
    'SIZE',
    'SORT_ARRAY',

    // conversion
    'BINARY',
    'CAST',

    // date
    'ADD_MONTHS',
    'DATE',
    'DATE_ADD',
    'DATE_FORMAT',
    'DATE_SUB',
    'DATEDIFF',
    'DAY',
    'DAYNAME',
    'DAYOFMONTH',
    'DAYOFYEAR',
    'EXTRACT',
    'FROM_UNIXTIME',
    'FROM_UTC_TIMESTAMP',
    'HOUR',
    'LAST_DAY',
    'MINUTE',
    'MONTH',
    'MONTHS_BETWEEN',
    'NEXT_DAY',
    'QUARTER',
    'SECOND',
    'TIMESTAMP',
    'TO_DATE',
    'TO_UTC_TIMESTAMP',
    'TRUNC',
    'UNIX_TIMESTAMP',
    'WEEKOFYEAR',
    'YEAR',

    // conditional
    'ASSERT_TRUE',
    'COALESCE',
    'IF',
    'ISNOTNULL',
    'ISNULL',
    'NULLIF',
    'NVL',

    // string
    'ASCII',
    'BASE64',
    'CHARACTER_LENGTH',
    'CHR',
    'CONCAT',
    'CONCAT_WS',
    'CONTEXT_NGRAMS',
    'DECODE',
    'ELT',
    'ENCODE',
    'FIELD',
    'FIND_IN_SET',
    'FORMAT_NUMBER',
    'GET_JSON_OBJECT',
    'IN_FILE',
    'INITCAP',
    'INSTR',
    'LCASE',
    'LENGTH',
    'LEVENSHTEIN',
    'LOCATE',
    'LOWER',
    'LPAD',
    'LTRIM',
    'NGRAMS',
    'OCTET_LENGTH',
    'PARSE_URL',
    'PRINTF',
    'QUOTE',
    'REGEXP_EXTRACT',
    'REGEXP_REPLACE',
    'REPEAT',
    'REVERSE',
    'RPAD',
    'RTRIM',
    'SENTENCES',
    'SOUNDEX',
    'SPACE',
    'SPLIT',
    'STR_TO_MAP',
    'SUBSTR',
    'SUBSTRING',
    'TRANSLATE',
    'TRIM',
    'UCASE',
    'UNBASE64',
    'UPPER',

    // masking
    'MASK',
    'MASK_FIRST_N',
    'MASK_HASH',
    'MASK_LAST_N',
    'MASK_SHOW_FIRST_N',
    'MASK_SHOW_LAST_N',

    // misc
    'AES_DECRYPT',
    'AES_ENCRYPT',
    'CRC32',
    'CURRENT_DATABASE',
    'CURRENT_USER',
    'HASH',
    'JAVA_METHOD',
    'LOGGED_IN_USER',
    'MD5',
    'REFLECT',
    'SHA',
    'SHA1',
    'SHA2',
    'SURROGATE_KEY',
    'VERSION',

    // aggregate
    'AVG',
    'COLLECT_LIST',
    'COLLECT_SET',
    'CORR',
    'COUNT',
    'COVAR_POP',
    'COVAR_SAMP',
    'HISTOGRAM_NUMERIC',
    'MAX',
    'MIN',
    'NTILE',
    'PERCENTILE',
    'PERCENTILE_APPROX',
    'REGR_AVGX',
    'REGR_AVGY',
    'REGR_COUNT',
    'REGR_INTERCEPT',
    'REGR_R2',
    'REGR_SLOPE',
    'REGR_SXX',
    'REGR_SXY',
    'REGR_SYY',
    'STDDEV_POP',
    'STDDEV_SAMP',
    'SUM',
    'VAR_POP',
    'VAR_SAMP',
    'VARIANCE',

    // table
    'EXPLODE',
    'INLINE',
    'JSON_TUPLE',
    'PARSE_URL_TUPLE',
    'POSEXPLODE',
    'STACK',

    // https://cwiki.apache.org/confluence/display/Hive/LanguageManual+WindowingAndAnalytics
    'LEAD',
    'LAG',
    'FIRST_VALUE',
    'LAST_VALUE',
    'RANK',
    'ROW_NUMBER',
    'DENSE_RANK',
    'CUME_DIST',
    'PERCENT_RANK',
    'NTILE'
];

export const functionSignatures: FunctionSignature[] = [
    // --- MATH (40) ---
    { name: 'ABS', params: ['double a'], returnType: 'double', description: '返回数值的绝对值', category: 'math' },
    { name: 'ACOS', params: ['double a'], returnType: 'double', description: '返回反余弦值', category: 'math' },
    { name: 'ASIN', params: ['double a'], returnType: 'double', description: '返回反正弦值', category: 'math' },
    { name: 'ATAN', params: ['double a'], returnType: 'double', description: '返回反正切值', category: 'math' },
    { name: 'BIN', params: ['bigint a'], returnType: 'string', description: '返回整数的二进制表示', category: 'math' },
    { name: 'BROUND', params: ['double a', 'int d'], returnType: 'double', description: '使用 HALF_EVEN 舍入模式四舍五入到 d 位小数', category: 'math' },
    { name: 'CBRT', params: ['double a'], returnType: 'double', description: '返回立方根', category: 'math' },
    { name: 'CEIL', params: ['double a'], returnType: 'bigint', description: '返回不小于 a 的最小整数（向上取整）', category: 'math' },
    { name: 'CEILING', params: ['double a'], returnType: 'bigint', description: 'CEIL 的别名，向上取整', category: 'math' },
    { name: 'CONV', params: ['string num', 'int from_base', 'int to_base'], returnType: 'string', description: '将数字从 from_base 进制转换为 to_base 进制', category: 'math' },
    { name: 'COS', params: ['double a'], returnType: 'double', description: '返回余弦值', category: 'math' },
    { name: 'DEGREES', params: ['double a'], returnType: 'double', description: '将弧度转换为角度', category: 'math' },
    { name: 'EXP', params: ['double a'], returnType: 'double', description: '返回 e 的 a 次幂', category: 'math' },
    { name: 'FACTORIAL', params: ['int a'], returnType: 'bigint', description: '返回 a 的阶乘', category: 'math' },
    { name: 'FLOOR', params: ['double a'], returnType: 'bigint', description: '返回不大于 a 的最大整数（向下取整）', category: 'math' },
    { name: 'GREATEST', params: ['T a', 'T b', '...'], returnType: 'T', description: '返回所有参数中的最大值', category: 'math' },
    { name: 'HEX', params: ['bigint|string a'], returnType: 'string', description: '返回整数或字符串的十六进制表示', category: 'math' },
    { name: 'LEAST', params: ['T a', 'T b', '...'], returnType: 'T', description: '返回所有参数中的最小值', category: 'math' },
    { name: 'LN', params: ['double a'], returnType: 'double', description: '返回 a 的自然对数', category: 'math' },
    { name: 'LOG', params: ['double base', 'double a'], returnType: 'double', description: '返回以 base 为底 a 的对数', category: 'math' },
    { name: 'LOG10', params: ['double a'], returnType: 'double', description: '返回 a 的以 10 为底的对数', category: 'math' },
    { name: 'LOG2', params: ['double a'], returnType: 'double', description: '返回 a 的以 2 为底的对数', category: 'math' },
    { name: 'NEGATIVE', params: ['T a'], returnType: 'T', description: '返回 -a', category: 'math' },
    { name: 'PI', params: [], returnType: 'double', description: '返回圆周率 π', category: 'math' },
    { name: 'PMOD', params: ['T a', 'T b'], returnType: 'T', description: '返回 a 除以 b 的正余数', category: 'math' },
    { name: 'POSITIVE', params: ['T a'], returnType: 'T', description: '返回 +a', category: 'math' },
    { name: 'POW', params: ['double a', 'double b'], returnType: 'double', description: '返回 a 的 b 次幂', category: 'math' },
    { name: 'POWER', params: ['double a', 'double b'], returnType: 'double', description: 'POW 的别名，返回 a 的 b 次幂', category: 'math' },
    { name: 'RADIANS', params: ['double a'], returnType: 'double', description: '将角度转换为弧度', category: 'math' },
    { name: 'RAND', params: ['int seed'], returnType: 'double', description: '返回 [0, 1) 之间的随机数，可指定种子', category: 'math' },
    { name: 'ROUND', params: ['double a', 'int d'], returnType: 'double', description: '将 a 四舍五入到 d 位小数', category: 'math' },
    { name: 'SHIFTLEFT', params: ['T a', 'int b'], returnType: 'T', description: '按位左移 b 位', category: 'math' },
    { name: 'SHIFTRIGHT', params: ['T a', 'int b'], returnType: 'T', description: '按位右移 b 位（算术移位）', category: 'math' },
    { name: 'SHIFTRIGHTUNSIGNED', params: ['T a', 'int b'], returnType: 'T', description: '按位无符号右移 b 位', category: 'math' },
    { name: 'SIGN', params: ['double a'], returnType: 'double', description: '返回 a 的符号（1.0/0.0/-1.0）', category: 'math' },
    { name: 'SIN', params: ['double a'], returnType: 'double', description: '返回正弦值', category: 'math' },
    { name: 'SQRT', params: ['double a'], returnType: 'double', description: '返回 a 的平方根', category: 'math' },
    { name: 'TAN', params: ['double a'], returnType: 'double', description: '返回正切值', category: 'math' },
    { name: 'UNHEX', params: ['string a'], returnType: 'string', description: '将十六进制字符串转为原始字符串', category: 'math' },
    { name: 'WIDTH_BUCKET', params: ['double expr', 'double min', 'double max', 'int buckets'], returnType: 'int', description: '返回 expr 在等宽直方图中的桶编号', category: 'math' },

    // --- COLLECTION (5) ---
    { name: 'ARRAY_CONTAINS', params: ['array<T> arr', 'T value'], returnType: 'boolean', description: '判断数组是否包含指定值', category: 'collection' },
    { name: 'MAP_KEYS', params: ['map<K,V> m'], returnType: 'array<K>', description: '返回 map 的所有键组成的数组', category: 'collection' },
    { name: 'MAP_VALUES', params: ['map<K,V> m'], returnType: 'array<V>', description: '返回 map 的所有值组成的数组', category: 'collection' },
    { name: 'SIZE', params: ['array<T>|map<K,V> a'], returnType: 'int', description: '返回数组长度或 map 的键值对数量', category: 'collection' },
    { name: 'SORT_ARRAY', params: ['array<T> arr'], returnType: 'array<T>', description: '对数组元素按升序排序', category: 'collection' },

    // --- TYPE CONVERSION (2) ---
    { name: 'BINARY', params: ['string|int a'], returnType: 'binary', description: '将参数转换为二进制类型', category: 'type-conversion' },
    { name: 'CAST', params: ['T expr', 'TYPE type'], returnType: 'TYPE', description: '将 expr 转换为指定类型', category: 'type-conversion' },

    // --- DATE (28) ---
    { name: 'ADD_MONTHS', params: ['date|string|timestamp start', 'int months'], returnType: 'string', description: '在日期上增加指定月数', category: 'date' },
    { name: 'DATE', params: ['string|timestamp ts'], returnType: 'date', description: '返回日期部分', category: 'date' },
    { name: 'DATE_ADD', params: ['date|string|timestamp start', 'int days'], returnType: 'string', description: '在日期上增加指定天数', category: 'date' },
    { name: 'DATE_FORMAT', params: ['date|string|timestamp date', 'string fmt'], returnType: 'string', description: '按指定格式将日期转为字符串', category: 'date' },
    { name: 'DATE_SUB', params: ['date|string|timestamp start', 'int days'], returnType: 'string', description: '在日期上减去指定天数', category: 'date' },
    { name: 'DATEDIFF', params: ['string enddate', 'string startdate'], returnType: 'int', description: '返回两个日期之间的天数差', category: 'date' },
    { name: 'DAY', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期中的日（1-31）', category: 'date' },
    { name: 'DAYNAME', params: ['date|string|timestamp date'], returnType: 'string', description: '返回日期的星期名称', category: 'date' },
    { name: 'DAYOFMONTH', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期是当月的第几天', category: 'date' },
    { name: 'DAYOFYEAR', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期是当年的第几天', category: 'date' },
    { name: 'EXTRACT', params: ['string unit', 'timestamp ts'], returnType: 'int', description: '从时间戳中提取指定时间单位的值', category: 'date' },
    { name: 'FROM_UNIXTIME', params: ['bigint unixtime', 'string format'], returnType: 'string', description: '将 Unix 时间戳转换为格式化字符串', category: 'date' },
    { name: 'FROM_UTC_TIMESTAMP', params: ['timestamp ts', 'string timezone'], returnType: 'timestamp', description: '将 UTC 时间戳转换为指定时区时间', category: 'date' },
    { name: 'HOUR', params: ['date|string|timestamp date'], returnType: 'int', description: '返回时间中的小时（0-23）', category: 'date' },
    { name: 'LAST_DAY', params: ['date|string|timestamp date'], returnType: 'string', description: '返回日期所在月份的最后一天', category: 'date' },
    { name: 'MINUTE', params: ['date|string|timestamp date'], returnType: 'int', description: '返回时间中的分钟（0-59）', category: 'date' },
    { name: 'MONTH', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期中的月份（1-12）', category: 'date' },
    { name: 'MONTHS_BETWEEN', params: ['date|string|timestamp date1', 'date|string|timestamp date2'], returnType: 'double', description: '返回两个日期之间的月数差', category: 'date' },
    { name: 'NEXT_DAY', params: ['string start_date', 'string day_of_week'], returnType: 'string', description: '返回 start_date 之后的下一个指定星期几的日期', category: 'date' },
    { name: 'QUARTER', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期所在的季度（1-4）', category: 'date' },
    { name: 'SECOND', params: ['date|string|timestamp date'], returnType: 'int', description: '返回时间中的秒数（0-59）', category: 'date' },
    { name: 'TIMESTAMP', params: ['string|date ts'], returnType: 'timestamp', description: '转换为 timestamp 类型', category: 'date' },
    { name: 'TO_DATE', params: ['string|timestamp ts'], returnType: 'date', description: '将字符串或时间戳转换为 date 类型', category: 'date' },
    { name: 'TO_UTC_TIMESTAMP', params: ['timestamp ts', 'string timezone'], returnType: 'timestamp', description: '将指定时区时间戳转换为 UTC', category: 'date' },
    { name: 'TRUNC', params: ['string date', 'string unit'], returnType: 'string', description: '将日期截断到指定精度', category: 'date' },
    { name: 'UNIX_TIMESTAMP', params: ['string date', 'string pattern'], returnType: 'bigint', description: '将日期字符串转换为 Unix 时间戳', category: 'date' },
    { name: 'WEEKOFYEAR', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期是当年的第几周', category: 'date' },
    { name: 'YEAR', params: ['date|string|timestamp date'], returnType: 'int', description: '返回日期中的年份', category: 'date' },

    // --- CONDITIONAL (7) ---
    { name: 'ASSERT_TRUE', params: ['boolean condition'], returnType: 'void', description: '如果条件为 false 则抛出异常', category: 'conditional' },
    { name: 'COALESCE', params: ['T v1', 'T v2', '...'], returnType: 'T', description: '返回参数列表中第一个非 NULL 值', category: 'conditional' },
    { name: 'IF', params: ['boolean condition', 'T true_val', 'T false_val'], returnType: 'T', description: '根据条件返回不同的值', category: 'conditional' },
    { name: 'ISNOTNULL', params: ['T a'], returnType: 'boolean', description: '判断 a 是否非 NULL', category: 'conditional' },
    { name: 'ISNULL', params: ['T a'], returnType: 'boolean', description: '判断 a 是否为 NULL', category: 'conditional' },
    { name: 'NULLIF', params: ['T a', 'T b'], returnType: 'T', description: '若 a=b 则返回 NULL，否则返回 a', category: 'conditional' },
    { name: 'NVL', params: ['T a', 'T default'], returnType: 'T', description: '若 a 为 NULL 则返回 default 值', category: 'conditional' },

    // --- STRING (46) ---
    { name: 'ASCII', params: ['string str'], returnType: 'int', description: '返回字符串第一个字符的 ASCII 码', category: 'string' },
    { name: 'BASE64', params: ['binary bin'], returnType: 'string', description: '将二进制数据编码为 Base64 字符串', category: 'string' },
    { name: 'CHARACTER_LENGTH', params: ['string str'], returnType: 'int', description: '返回字符串的字符长度', category: 'string' },
    { name: 'CHR', params: ['bigint|double a'], returnType: 'string', description: '返回 ASCII 码对应的字符', category: 'string' },
    { name: 'CONCAT', params: ['string str1', 'string str2', '...'], returnType: 'string', description: '连接多个字符串', category: 'string' },
    { name: 'CONCAT_WS', params: ['string sep', 'string str1', 'string str2', '...'], returnType: 'string', description: '使用指定分隔符连接多个字符串', category: 'string' },
    { name: 'CONTEXT_NGRAMS', params: ['array<array<string>> sentences', 'array<string> words', 'int k'], returnType: 'array<struct>', description: '给定句子和单词，返回前 k 个上下文 n-gram', category: 'string' },
    { name: 'DECODE', params: ['binary bin', 'string charset'], returnType: 'string', description: '使用指定字符集解码二进制数据', category: 'string' },
    { name: 'ELT', params: ['int n', 'string str1', 'string str2', '...'], returnType: 'string', description: '返回参数列表中第 n 个字符串', category: 'string' },
    { name: 'ENCODE', params: ['string str', 'string charset'], returnType: 'binary', description: '使用指定字符集编码字符串为二进制', category: 'string' },
    { name: 'FIELD', params: ['T val', 'T val1', 'T val2', '...'], returnType: 'int', description: '返回 val 在参数列表中的位置（从 1 开始）', category: 'string' },
    { name: 'FIND_IN_SET', params: ['string str', 'string strlist'], returnType: 'int', description: '返回 str 在逗号分隔列表中的位置', category: 'string' },
    { name: 'FORMAT_NUMBER', params: ['number x', 'int d'], returnType: 'string', description: '将数字格式化为 #,###.## 格式', category: 'string' },
    { name: 'IN_FILE', params: ['string str', 'string filename'], returnType: 'boolean', description: '判断 str 是否出现在文件中', category: 'string' },
    { name: 'INITCAP', params: ['string str'], returnType: 'string', description: '返回每个单词首字母大写的字符串', category: 'string' },
    { name: 'INSTR', params: ['string str', 'string substr'], returnType: 'int', description: '返回子串首次出现的位置（从 1 开始）', category: 'string' },
    { name: 'LCASE', params: ['string str'], returnType: 'string', description: 'LOWER 的别名，返回小写字符串', category: 'string' },
    { name: 'LENGTH', params: ['string str'], returnType: 'int', description: '返回字符串的长度（字符数）', category: 'string' },
    { name: 'LEVENSHTEIN', params: ['string str1', 'string str2'], returnType: 'int', description: '返回两个字符串的编辑距离', category: 'string' },
    { name: 'LOCATE', params: ['string substr', 'string str', 'int pos'], returnType: 'int', description: '返回子串在字符串中从 pos 开始首次出现的位置', category: 'string' },
    { name: 'LOWER', params: ['string str'], returnType: 'string', description: '返回全小写的字符串', category: 'string' },
    { name: 'LPAD', params: ['string str', 'int len', 'string pad'], returnType: 'string', description: '在左侧用 pad 填充至指定长度', category: 'string' },
    { name: 'LTRIM', params: ['string str'], returnType: 'string', description: '去除字符串左侧的空白字符', category: 'string' },
    { name: 'NGRAMS', params: ['array<array<string>> sentences', 'int n', 'int k'], returnType: 'array<struct>', description: '从句子中返回前 k 个 n-gram', category: 'string' },
    { name: 'OCTET_LENGTH', params: ['string str'], returnType: 'int', description: '返回字符串的字节数', category: 'string' },
    { name: 'PARSE_URL', params: ['string url', 'string part'], returnType: 'string', description: '从 URL 中提取指定部分（HOST/PATH/QUERY 等）', category: 'string' },
    { name: 'PRINTF', params: ['string format', '... values'], returnType: 'string', description: '返回格式化后的字符串（C 语言 printf 风格）', category: 'string' },
    { name: 'QUOTE', params: ['string str'], returnType: 'string', description: '为字符串加上引号并进行转义', category: 'string' },
    { name: 'REGEXP_EXTRACT', params: ['string str', 'string pattern', 'int index'], returnType: 'string', description: '提取字符串中匹配正则表达式的第 index 个捕获组', category: 'string' },
    { name: 'REGEXP_REPLACE', params: ['string str', 'string pattern', 'string replacement'], returnType: 'string', description: '用 replacement 替换字符串中匹配 pattern 的部分', category: 'string' },
    { name: 'REPEAT', params: ['string str', 'int n'], returnType: 'string', description: '重复 str 字符串 n 次', category: 'string' },
    { name: 'REVERSE', params: ['string str'], returnType: 'string', description: '反转字符串', category: 'string' },
    { name: 'RPAD', params: ['string str', 'int len', 'string pad'], returnType: 'string', description: '在右侧用 pad 填充至指定长度', category: 'string' },
    { name: 'RTRIM', params: ['string str'], returnType: 'string', description: '去除字符串右侧的空白字符', category: 'string' },
    { name: 'SENTENCES', params: ['string str', 'string lang', 'string locale'], returnType: 'array<string>', description: '将文本按照语言分句为一组句子', category: 'string' },
    { name: 'SOUNDEX', params: ['string str'], returnType: 'string', description: '返回字符串的 Soundex 编码', category: 'string' },
    { name: 'SPACE', params: ['int n'], returnType: 'string', description: '返回包含 n 个空格的字符串', category: 'string' },
    { name: 'SPLIT', params: ['string str', 'string pattern'], returnType: 'array<string>', description: '按正则表达式拆分字符串为数组', category: 'string' },
    { name: 'STR_TO_MAP', params: ['string str', 'string delim1', 'string delim2'], returnType: 'map<string,string>', description: '将分隔字符串转换为 map', category: 'string' },
    { name: 'SUBSTR', params: ['string str', 'int start', 'int length'], returnType: 'string', description: '返回从 start 开始指定长度的子串', category: 'string' },
    { name: 'SUBSTRING', params: ['string str', 'int start', 'int length'], returnType: 'string', description: 'SUBSTR 的别名，返回子串', category: 'string' },
    { name: 'TRANSLATE', params: ['string input', 'string from', 'string to'], returnType: 'string', description: '将 input 中 from 的字符一一替换为 to 中的字符', category: 'string' },
    { name: 'TRIM', params: ['string str'], returnType: 'string', description: '去除字符串两侧的空白字符', category: 'string' },
    { name: 'UCASE', params: ['string str'], returnType: 'string', description: 'UPPER 的别名，返回全大写字符串', category: 'string' },
    { name: 'UNBASE64', params: ['string str'], returnType: 'binary', description: '将 Base64 字符串解码为二进制', category: 'string' },
    { name: 'UPPER', params: ['string str'], returnType: 'string', description: '返回全大写的字符串', category: 'string' },

    // --- JSON (1) ---
    { name: 'GET_JSON_OBJECT', params: ['string json_str', 'string path'], returnType: 'string', description: '从 JSON 字符串中按路径提取值', category: 'json' },

    // --- ENCRYPTION (13) ---
    { name: 'MASK', params: ['string str', 'string upper', 'string lower', 'string number'], returnType: 'string', description: '对字符串进行脱敏处理', category: 'encryption' },
    { name: 'MASK_FIRST_N', params: ['string str', 'int n'], returnType: 'string', description: '对前 n 个字符进行脱敏', category: 'encryption' },
    { name: 'MASK_HASH', params: ['string str'], returnType: 'string', description: '返回字符串的哈希脱敏值', category: 'encryption' },
    { name: 'MASK_LAST_N', params: ['string str', 'int n'], returnType: 'string', description: '对后 n 个字符进行脱敏', category: 'encryption' },
    { name: 'MASK_SHOW_FIRST_N', params: ['string str', 'int n'], returnType: 'string', description: '显示前 n 个字符，其余脱敏', category: 'encryption' },
    { name: 'MASK_SHOW_LAST_N', params: ['string str', 'int n'], returnType: 'string', description: '显示后 n 个字符，其余脱敏', category: 'encryption' },
    { name: 'AES_DECRYPT', params: ['binary input', 'string key'], returnType: 'binary', description: '使用 AES 算法解密数据', category: 'encryption' },
    { name: 'AES_ENCRYPT', params: ['string input', 'string key'], returnType: 'binary', description: '使用 AES 算法加密数据', category: 'encryption' },
    { name: 'CRC32', params: ['string|binary str'], returnType: 'bigint', description: '返回字符串的 CRC32 校验值', category: 'encryption' },
    { name: 'MD5', params: ['string|binary str'], returnType: 'string', description: '返回字符串的 MD5 哈希值', category: 'encryption' },
    { name: 'SHA', params: ['string|binary str'], returnType: 'string', description: '返回字符串的 SHA-1 哈希值', category: 'encryption' },
    { name: 'SHA1', params: ['string|binary str'], returnType: 'string', description: 'SHA 的别名，返回 SHA-1 哈希值', category: 'encryption' },
    { name: 'SHA2', params: ['string|binary str', 'int bitLength'], returnType: 'string', description: '返回 SHA-2 哈希值（224/256/384/512）', category: 'encryption' },

    // --- OTHER (8) ---
    { name: 'CURRENT_DATABASE', params: [], returnType: 'string', description: '返回当前数据库名称', category: 'other' },
    { name: 'CURRENT_USER', params: [], returnType: 'string', description: '返回当前用户名', category: 'other' },
    { name: 'HASH', params: ['T a', 'T b', '...'], returnType: 'int', description: '返回所有参数的哈希值', category: 'other' },
    { name: 'JAVA_METHOD', params: ['string class', 'string method', '...'], returnType: 'T', description: '调用 Java 类中的静态方法', category: 'other' },
    { name: 'LOGGED_IN_USER', params: [], returnType: 'string', description: '返回已登录用户名', category: 'other' },
    { name: 'REFLECT', params: ['string class', 'string method', '...'], returnType: 'T', description: '通过反射调用 Java 方法', category: 'other' },
    { name: 'SURROGATE_KEY', params: [], returnType: 'bigint', description: '生成自增的代理键', category: 'other' },
    { name: 'VERSION', params: [], returnType: 'string', description: '返回 Hive 版本信息', category: 'other' },

    // --- AGGREGATE (28) ---
    { name: 'AVG', params: ['T col'], returnType: 'double', description: '返回列的平均值', category: 'aggregate' },
    { name: 'COLLECT_LIST', params: ['T col'], returnType: 'array<T>', description: '返回列的所有值组成的数组（含重复）', category: 'aggregate' },
    { name: 'COLLECT_SET', params: ['T col'], returnType: 'array<T>', description: '返回列的去重值组成的数组', category: 'aggregate' },
    { name: 'CORR', params: ['T col1', 'T col2'], returnType: 'double', description: '返回两列的皮尔逊相关系数', category: 'aggregate' },
    { name: 'COUNT', params: ['*|T col', 'T col2', '...'], returnType: 'bigint', description: '返回行数或非 NULL 行数', category: 'aggregate' },
    { name: 'COVAR_POP', params: ['T col1', 'T col2'], returnType: 'double', description: '返回两列的总体协方差', category: 'aggregate' },
    { name: 'COVAR_SAMP', params: ['T col1', 'T col2'], returnType: 'double', description: '返回两列的样本协方差', category: 'aggregate' },
    { name: 'HISTOGRAM_NUMERIC', params: ['T col', 'int nb'], returnType: 'array<struct>', description: '返回数值列的等宽直方图', category: 'aggregate' },
    { name: 'MAX', params: ['T col'], returnType: 'T', description: '返回列的最大值', category: 'aggregate' },
    { name: 'MIN', params: ['T col'], returnType: 'T', description: '返回列的最小值', category: 'aggregate' },
    { name: 'NTILE', params: ['int n'], returnType: 'int', description: '将行分配到 n 个桶中，返回桶编号', category: 'window' },
    { name: 'PERCENTILE', params: ['bigint col', 'double p'], returnType: 'double', description: '返回列的第 p 个百分位数', category: 'aggregate' },
    { name: 'PERCENTILE_APPROX', params: ['T col', 'double p'], returnType: 'double', description: '返回列的近似第 p 个百分位数', category: 'aggregate' },
    { name: 'REGR_AVGX', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回独立变量的均值', category: 'aggregate' },
    { name: 'REGR_AVGY', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回因变量的均值', category: 'aggregate' },
    { name: 'REGR_COUNT', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回用于回归的非 NULL 行数', category: 'aggregate' },
    { name: 'REGR_INTERCEPT', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回线性回归的 y 截距', category: 'aggregate' },
    { name: 'REGR_R2', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回线性回归的 R 平方决定系数', category: 'aggregate' },
    { name: 'REGR_SLOPE', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回线性回归的斜率', category: 'aggregate' },
    { name: 'REGR_SXX', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回独立变量的平方和', category: 'aggregate' },
    { name: 'REGR_SXY', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回独立变量和因变量的乘积和', category: 'aggregate' },
    { name: 'REGR_SYY', params: ['T independent', 'T dependent'], returnType: 'double', description: '返回因变量的平方和', category: 'aggregate' },
    { name: 'STDDEV_POP', params: ['T col'], returnType: 'double', description: '返回列的总体标准差', category: 'aggregate' },
    { name: 'STDDEV_SAMP', params: ['T col'], returnType: 'double', description: '返回列的样本标准差', category: 'aggregate' },
    { name: 'SUM', params: ['T col'], returnType: 'T', description: '返回列的总和', category: 'aggregate' },
    { name: 'VAR_POP', params: ['T col'], returnType: 'double', description: '返回列的总体方差', category: 'aggregate' },
    { name: 'VAR_SAMP', params: ['T col'], returnType: 'double', description: '返回列的样本方差', category: 'aggregate' },
    { name: 'VARIANCE', params: ['T col'], returnType: 'double', description: 'VAR_POP 的别名', category: 'aggregate' },

    // --- TABLE (6) ---
    { name: 'EXPLODE', params: ['array<T>|map<K,V> a'], returnType: '多行 T 或 (K,V)', description: '将数组或 map 元素展开为多行', category: 'table' },
    { name: 'INLINE', params: ['array<struct> a'], returnType: '多行 struct 字段', description: '将结构体数组展开为多行多列', category: 'table' },
    { name: 'JSON_TUPLE', params: ['string json', 'string k1', 'string k2', '...'], returnType: '多列', description: '从 JSON 字符串中提取多个字段，返回元组', category: 'table' },
    { name: 'PARSE_URL_TUPLE', params: ['string url', 'string p1', 'string p2', '...'], returnType: '多列', description: '从 URL 中提取多个部分，返回元组', category: 'table' },
    { name: 'POSEXPLODE', params: ['array<T>|map<K,V> a'], returnType: '多行 (pos,val)', description: '类似 EXPLODE 但额外返回元素位置', category: 'table' },
    { name: 'STACK', params: ['int n', 'T v1', 'T v2', '...'], returnType: '多行', description: '将值分割成 n 行', category: 'table' },

    // --- WINDOW (9) ---
    { name: 'LEAD', params: ['T col', 'int offset', 'T default'], returnType: 'T', description: '返回当前行之后 offset 行的值', category: 'window' },
    { name: 'LAG', params: ['T col', 'int offset', 'T default'], returnType: 'T', description: '返回当前行之前 offset 行的值', category: 'window' },
    { name: 'FIRST_VALUE', params: ['T col', 'boolean ignoreNulls'], returnType: 'T', description: '返回窗口内第一行的值', category: 'window' },
    { name: 'LAST_VALUE', params: ['T col', 'boolean ignoreNulls'], returnType: 'T', description: '返回窗口内最后一行的值', category: 'window' },
    { name: 'RANK', params: [], returnType: 'int', description: '返回排序名次（相同值同名次，有间隔）', category: 'window' },
    { name: 'ROW_NUMBER', params: [], returnType: 'int', description: '返回行号（从 1 开始，无重复）', category: 'window' },
    { name: 'DENSE_RANK', params: [], returnType: 'int', description: '返回排序名次（相同值同名次，无间隔）', category: 'window' },
    { name: 'CUME_DIST', params: [], returnType: 'double', description: '返回累积分布值（0-1）', category: 'window' },
    { name: 'PERCENT_RANK', params: [], returnType: 'double', description: '返回相对排名百分比（0-1）', category: 'window' },
];
