import type { KeywordInfo } from '../../hover/HoverResolver'

export const baseKeywords: KeywordInfo[] = [
    { keyword: 'SELECT', syntax: 'SELECT [DISTINCT] expr1, expr2, ... FROM table', description: '从表或视图中查询数据', category: 'query', example: 'SELECT name, age FROM employees WHERE dept = \'IT\'' },
    { keyword: 'FROM', syntax: 'FROM table_name [alias]', description: '指定查询的数据源表或视图', category: 'query' },
    { keyword: 'WHERE', syntax: 'WHERE condition', description: '指定查询的过滤条件', category: 'query', example: 'SELECT * FROM employees WHERE salary > 5000' },
    { keyword: 'GROUP BY', syntax: 'GROUP BY expr1, expr2, ...', description: '按一个或多个列对结果集进行分组', category: 'query', example: 'SELECT dept, COUNT(*) FROM employees GROUP BY dept' },
    { keyword: 'HAVING', syntax: 'HAVING condition', description: '对分组后的结果进行过滤（类似于 WHERE，但用于聚合后）', category: 'query', example: 'SELECT dept, COUNT(*) AS cnt FROM employees GROUP BY dept HAVING cnt > 5' },
    { keyword: 'ORDER BY', syntax: 'ORDER BY expr [ASC|DESC], ...', description: '对结果集按一个或多个列排序', category: 'query', example: 'SELECT name, salary FROM employees ORDER BY salary DESC' },
    { keyword: 'LIMIT', syntax: 'LIMIT n', description: '限制查询返回的行数', category: 'query', example: 'SELECT * FROM employees ORDER BY salary DESC LIMIT 10' },
    { keyword: 'OFFSET', syntax: 'OFFSET n', description: '跳过前 n 行结果，常与 LIMIT 配合实现分页', category: 'query' },
    { keyword: 'DISTINCT', syntax: 'SELECT DISTINCT expr1, expr2, ...', description: '去除查询结果中的重复行', category: 'query', example: 'SELECT DISTINCT dept FROM employees' },
    { keyword: 'AS', syntax: 'expr AS alias', description: '为列或表指定别名', category: 'query', example: 'SELECT COUNT(*) AS total FROM employees' },
    { keyword: 'ALL', syntax: 'SELECT ALL expr ...', description: '保留所有行（默认行为，与 DISTINCT 相对）', category: 'query' },
    { keyword: 'ANY', syntax: 'expr operator ANY (subquery)', description: '如果子查询中有任意一行满足条件则返回 true', category: 'query' },
    { keyword: 'SOME', syntax: 'expr operator SOME (subquery)', description: 'ANY 的同义词', category: 'query' },
    { keyword: 'EXISTS', syntax: 'EXISTS (subquery)', description: '判断子查询是否返回任何行', category: 'query', example: 'SELECT * FROM orders WHERE EXISTS (SELECT 1 FROM customers WHERE customers.id = orders.customer_id)' },
    { keyword: 'BETWEEN', syntax: 'expr BETWEEN low AND high', description: '判断值是否在指定范围内', category: 'query', example: 'SELECT * FROM employees WHERE salary BETWEEN 3000 AND 8000' },
    { keyword: 'LIKE', syntax: 'expr LIKE pattern', description: '使用通配符进行模式匹配（% 任意字符，_ 单个字符）', category: 'query', example: 'SELECT * FROM employees WHERE name LIKE \'张%\'' },
    { keyword: 'IN', syntax: 'expr IN (value1, value2, ...)', description: '判断值是否在指定列表或子查询结果中', category: 'query', example: 'SELECT * FROM employees WHERE dept IN (\'IT\', \'HR\')' },
    { keyword: 'IS NULL', syntax: 'expr IS NULL', description: '判断值是否为 NULL', category: 'query', example: 'SELECT * FROM employees WHERE manager_id IS NULL' },
    { keyword: 'IS NOT NULL', syntax: 'expr IS NOT NULL', description: '判断值是否不为 NULL', category: 'query' },
    { keyword: 'AND', syntax: 'condition1 AND condition2', description: '逻辑与，两个条件同时满足', category: 'query' },
    { keyword: 'OR', syntax: 'condition1 OR condition2', description: '逻辑或，任一条件满足即可', category: 'query' },
    { keyword: 'NOT', syntax: 'NOT condition', description: '逻辑非，取反条件', category: 'query' },
    { keyword: 'JOIN', syntax: 'SELECT ... FROM table1 [INNER|LEFT|RIGHT|FULL|CROSS] JOIN table2 ON condition', description: '用于根据两个或多个表之间的相关列来组合行', category: 'join', example: 'SELECT a.name, b.order_id\nFROM customers a\nINNER JOIN orders b ON a.id = b.customer_id' },
    { keyword: 'INNER JOIN', syntax: 'table1 INNER JOIN table2 ON condition', description: '内连接，仅返回两表中匹配的行', category: 'join', example: 'SELECT a.name, b.order_id FROM customers a INNER JOIN orders b ON a.id = b.customer_id' },
    { keyword: 'LEFT JOIN', syntax: 'table1 LEFT [OUTER] JOIN table2 ON condition', description: '左外连接，返回左表所有行，右表无匹配则为 NULL', category: 'join', example: 'SELECT a.name, b.order_id FROM customers a LEFT JOIN orders b ON a.id = b.customer_id' },
    { keyword: 'RIGHT JOIN', syntax: 'table1 RIGHT [OUTER] JOIN table2 ON condition', description: '右外连接，返回右表所有行，左表无匹配则为 NULL', category: 'join' },
    { keyword: 'FULL JOIN', syntax: 'table1 FULL [OUTER] JOIN table2 ON condition', description: '全外连接，返回两表所有行，无匹配则为 NULL', category: 'join' },
    { keyword: 'CROSS JOIN', syntax: 'table1 CROSS JOIN table2', description: '交叉连接，返回两表的笛卡尔积', category: 'join' },
    { keyword: 'NATURAL JOIN', syntax: 'table1 NATURAL JOIN table2', description: '自然连接，自动按两表同名列进行等值连接', category: 'join' },
    { keyword: 'ON', syntax: 'JOIN table2 ON condition', description: '指定连接条件', category: 'join' },
    { keyword: 'USING', syntax: 'JOIN table2 USING (column)', description: '使用同名列进行连接的简写', category: 'join' },
    { keyword: 'UNION', syntax: 'query1 UNION query2', description: '合并两个查询结果集并去除重复行', category: 'setop', example: 'SELECT name FROM employees UNION SELECT name FROM contractors' },
    { keyword: 'UNION ALL', syntax: 'query1 UNION ALL query2', description: '合并两个查询结果集，保留所有行（不去重）', category: 'setop', example: 'SELECT name FROM employees UNION ALL SELECT name FROM contractors' },
    { keyword: 'INTERSECT', syntax: 'query1 INTERSECT query2', description: '返回两个查询结果集的交集', category: 'setop' },
    { keyword: 'EXCEPT', syntax: 'query1 EXCEPT query2', description: '返回在第一个查询中但不在第二个查询中的行', category: 'setop' },
    { keyword: 'MINUS', syntax: 'query1 MINUS query2', description: 'EXCEPT 的同义词（Oracle 语法）', category: 'setop' },
    { keyword: 'INSERT INTO', syntax: 'INSERT INTO table (col1, col2) VALUES (val1, val2)', description: '向表中插入数据', category: 'dml', example: 'INSERT INTO employees (name, dept) VALUES (\'Alice\', \'IT\')' },
    { keyword: 'INSERT OVERWRITE', syntax: 'INSERT OVERWRITE TABLE target SELECT ...', description: '覆盖写入目标表数据（Hive/Spark）', category: 'dml', example: 'INSERT OVERWRITE TABLE target_table SELECT * FROM source_table' },
    { keyword: 'UPDATE', syntax: 'UPDATE table SET col1 = val1 WHERE condition', description: '修改表中满足条件的行', category: 'dml', example: 'UPDATE employees SET salary = 6000 WHERE name = \'Alice\'' },
    { keyword: 'DELETE', syntax: 'DELETE FROM table WHERE condition', description: '删除表中满足条件的行', category: 'dml', example: 'DELETE FROM employees WHERE dept = \'HR\'' },
    { keyword: 'MERGE', syntax: 'MERGE INTO target USING source ON condition WHEN MATCHED THEN ... WHEN NOT MATCHED THEN ...', description: '根据条件对目标表执行插入或更新操作', category: 'dml' },
    { keyword: 'TRUNCATE', syntax: 'TRUNCATE TABLE table_name', description: '清空表中的所有数据，但保留表结构', category: 'dml' },
    { keyword: 'VALUES', syntax: 'VALUES (val1, val2), (val3, val4)', description: '定义行值表达式，常用于 INSERT', category: 'dml' },
    { keyword: 'CREATE TABLE', syntax: 'CREATE TABLE [IF NOT EXISTS] table_name (col1 type, col2 type, ...)', description: '创建新表', category: 'ddl', example: 'CREATE TABLE employees (\n  id INT,\n  name STRING,\n  salary DECIMAL(10,2)\n)' },
    { keyword: 'CREATE VIEW', syntax: 'CREATE VIEW view_name AS SELECT ...', description: '创建视图', category: 'ddl' },
    { keyword: 'ALTER TABLE', syntax: 'ALTER TABLE table_name action', description: '修改表结构或属性', category: 'ddl', example: 'ALTER TABLE employees ADD COLUMN email STRING' },
    { keyword: 'DROP TABLE', syntax: 'DROP TABLE [IF EXISTS] table_name', description: '删除表及其所有数据', category: 'ddl' },
    { keyword: 'DROP VIEW', syntax: 'DROP VIEW [IF EXISTS] view_name', description: '删除视图', category: 'ddl' },
    { keyword: 'OVER', syntax: 'window_function() OVER ([PARTITION BY expr] [ORDER BY expr [frame_clause]])', description: '定义窗口函数的窗口规范', category: 'window', example: 'SELECT name, salary, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) AS rank\nFROM employees' },
    { keyword: 'PARTITION BY', syntax: 'PARTITION BY expr1, expr2, ...', description: '在窗口函数中将结果集分区', category: 'window' },
    { keyword: 'ROWS BETWEEN', syntax: 'ROWS BETWEEN start AND end', description: '定义窗口的行范围框架', category: 'window' },
    { keyword: 'RANGE BETWEEN', syntax: 'RANGE BETWEEN start AND end', description: '定义窗口的值范围框架', category: 'window' },
    { keyword: 'UNBOUNDED PRECEDING', syntax: 'ROWS BETWEEN UNBOUNDED PRECEDING AND ...', description: '窗口框架起始边界，表示分区第一行', category: 'window' },
    { keyword: 'CURRENT ROW', syntax: 'ROWS BETWEEN ... AND CURRENT ROW', description: '窗口框架边界，表示当前行', category: 'window' },
    { keyword: 'UNBOUNDED FOLLOWING', syntax: 'ROWS BETWEEN ... AND UNBOUNDED FOLLOWING', description: '窗口框架结束边界，表示分区最后一行', category: 'window' },
    { keyword: 'BEGIN', syntax: 'BEGIN [TRANSACTION | WORK]', description: '开始一个事务', category: 'transaction' },
    { keyword: 'COMMIT', syntax: 'COMMIT [TRANSACTION | WORK]', description: '提交当前事务', category: 'transaction' },
    { keyword: 'ROLLBACK', syntax: 'ROLLBACK [TRANSACTION | WORK]', description: '回滚当前事务', category: 'transaction' },
    { keyword: 'SAVEPOINT', syntax: 'SAVEPOINT savepoint_name', description: '在事务中设置保存点', category: 'transaction' },
    { keyword: 'SHOW', syntax: 'SHOW TABLES | SHOW DATABASES | SHOW PARTITIONS table', description: '显示数据库对象信息', category: 'auxiliary', example: 'SHOW TABLES' },
    { keyword: 'DESCRIBE', syntax: 'DESCRIBE [FORMATTED|EXTENDED] table_name', description: '显示表或列的结构信息', category: 'auxiliary', example: 'DESCRIBE FORMATTED employees' },
    { keyword: 'EXPLAIN', syntax: 'EXPLAIN [EXTENDED] query', description: '显示查询的执行计划', category: 'auxiliary' },
    { keyword: 'ANALYZE', syntax: 'ANALYZE TABLE table_name COMPUTE STATISTICS', description: '收集表的统计信息', category: 'auxiliary' },
    { keyword: 'USE', syntax: 'USE database_name', description: '切换当前数据库', category: 'auxiliary', example: 'USE my_database' },
    { keyword: 'SET', syntax: 'SET key = value | SET -v', description: '设置或显示配置参数', category: 'auxiliary' },
    { keyword: 'CASE', syntax: 'CASE WHEN condition THEN result [WHEN ... THEN ...] ELSE result END', description: '条件表达式，根据条件返回不同的值', category: 'conditional', example: 'SELECT name,\n  CASE WHEN salary > 8000 THEN \'高\'\n       WHEN salary > 5000 THEN \'中\'\n       ELSE \'低\'\n  END AS level\nFROM employees' },
    { keyword: 'WHEN', syntax: 'CASE WHEN condition THEN result', description: 'CASE 表达式中的条件分支', category: 'conditional' },
    { keyword: 'THEN', syntax: 'WHEN condition THEN result', description: 'CASE 表达式中条件成立时的返回值', category: 'conditional' },
    { keyword: 'ELSE', syntax: 'CASE ... ELSE default_result END', description: 'CASE 表达式中所有条件不满足时的默认值', category: 'conditional' },
    { keyword: 'END', syntax: 'CASE ... END', description: '结束 CASE 表达式', category: 'conditional' },
    { keyword: 'IF', syntax: 'IF(condition, true_value, false_value)', description: '条件函数，根据条件返回不同的值', category: 'conditional', example: 'SELECT IF(salary > 5000, \'高\', \'低\') AS level FROM employees' },
    { keyword: 'COALESCE', syntax: 'COALESCE(val1, val2, ...)', description: '返回参数列表中第一个非 NULL 的值', category: 'conditional', example: 'SELECT COALESCE(phone, email, \'N/A\') AS contact FROM employees' },
    { keyword: 'NULLIF', syntax: 'NULLIF(expr1, expr2)', description: '如果两个表达式相等则返回 NULL，否则返回第一个表达式', category: 'conditional' },
    { keyword: 'INT', syntax: 'INT', description: '整数类型，通常为 4 字节', category: 'type' },
    { keyword: 'BIGINT', syntax: 'BIGINT', description: '大整数类型，通常为 8 字节', category: 'type' },
    { keyword: 'STRING', syntax: 'STRING', description: '可变长度字符串类型（Hive）', category: 'type' },
    { keyword: 'VARCHAR', syntax: 'VARCHAR(n)', description: '可变长度字符串类型，最大长度 n', category: 'type' },
    { keyword: 'CHAR', syntax: 'CHAR(n)', description: '定长字符串类型，长度 n', category: 'type' },
    { keyword: 'BOOLEAN', syntax: 'BOOLEAN', description: '布尔类型，值为 TRUE 或 FALSE', category: 'type' },
    { keyword: 'DOUBLE', syntax: 'DOUBLE', description: '双精度浮点数类型', category: 'type' },
    { keyword: 'FLOAT', syntax: 'FLOAT', description: '单精度浮点数类型', category: 'type' },
    { keyword: 'DECIMAL', syntax: 'DECIMAL(precision, scale)', description: '精确数值类型，指定精度和小数位数', category: 'type', example: 'DECIMAL(10, 2)' },
    { keyword: 'DATE', syntax: 'DATE', description: '日期类型（年-月-日）', category: 'type' },
    { keyword: 'TIMESTAMP', syntax: 'TIMESTAMP', description: '时间戳类型（日期+时间）', category: 'type' },
    { keyword: 'ARRAY', syntax: 'ARRAY<type>', description: '数组类型，存储同类型元素的有序集合', category: 'type', example: 'ARRAY<STRING>' },
    { keyword: 'MAP', syntax: 'MAP<key_type, value_type>', description: '映射类型，存储键值对集合', category: 'type', example: 'MAP<STRING, INT>' },
    { keyword: 'STRUCT', syntax: 'STRUCT<field1: type1, field2: type2, ...>', description: '结构体类型，存储具名字段集合', category: 'type', example: 'STRUCT<name: STRING, age: INT>' },
]
