import type { KeywordInfo } from "../../hover/HoverResolver";

// Dameng (达梦 DM8) specific keyword info for hover/completion.
// Dameng is Oracle-compatible but adds MySQL-compat features like TOP/LIMIT.
export const damengKeywords: KeywordInfo[] = [
    {
        keyword: "DUAL",
        syntax: "SELECT expr FROM DUAL",
        description: "达梦提供的虚拟单行表，用于无需业务表的 SELECT",
        category: "query",
        example: "SELECT SYSDATE FROM DUAL",
    },
    {
        keyword: "ROWNUM",
        syntax: "WHERE ROWNUM <= n",
        description: "伪列，返回结果集中行的序号（在排序前分配）",
        category: "query",
        example: "SELECT * FROM employees WHERE ROWNUM <= 10",
    },
    {
        keyword: "TOP",
        syntax: "SELECT TOP (n) ...",
        description: "达梦 MySQL 兼容模式下的行数限制（与 ROWNUM 互斥使用）",
        category: "query",
        example: "SELECT TOP 10 * FROM employees",
    },
    {
        keyword: "LIMIT",
        syntax: "SELECT ... LIMIT n [OFFSET m]",
        description: "达梦 MySQL 兼容模式下的分页语法",
        category: "query",
        example: "SELECT * FROM employees LIMIT 10 OFFSET 20",
    },
    { keyword: "ROWID", syntax: "SELECT ROWID, ... FROM table", description: "伪列，行的物理存储地址标识符", category: "query" },
    {
        keyword: "SYSDATE",
        syntax: "SYSDATE",
        description: "返回当前会话时区的日期时间",
        category: "auxiliary",
        example: "SELECT SYSDATE FROM DUAL",
    },
    {
        keyword: "SEQUENCE",
        syntax: "CREATE SEQUENCE name START WITH n INCREMENT BY m",
        description: "用户定义的序列对象，通过 NEXTVAL/CURRVAL 取值",
        category: "ddl",
        example: "CREATE SEQUENCE seq_orders START WITH 1 INCREMENT BY 1",
    },
    {
        keyword: "NEXTVAL",
        syntax: "sequence.NEXTVAL",
        description: "取序列的下一个值",
        category: "auxiliary",
        example: "INSERT INTO orders(id) VALUES (seq_orders.NEXTVAL)",
    },
    { keyword: "CURRVAL", syntax: "sequence.CURRVAL", description: "取序列在当前会话的当前值（需先调用 NEXTVAL）", category: "auxiliary" },
    {
        keyword: "SYNONYM",
        syntax: "CREATE [OR REPLACE] [PUBLIC] SYNONYM name FOR object",
        description: "为对象创建别名",
        category: "ddl",
        example: "CREATE SYNONYM emp FOR hr.employees",
    },
    {
        keyword: "DBLINK",
        syntax: "CREATE DATABASE LINK name CONNECT TO user IDENTIFIED BY pwd USING 'service'",
        description: "数据库链路，用于访问远程数据库",
        category: "ddl",
        example: "CREATE DATABASE LINK link1 CONNECT TO remote_user IDENTIFIED BY pwd USING 'remote_service'",
    },
    {
        keyword: "MINUS",
        syntax: "SELECT ... MINUS SELECT ...",
        description: "集合差运算（达梦等价于标准 SQL 的 EXCEPT）",
        category: "query",
        example: "SELECT id FROM a MINUS SELECT id FROM b",
    },
    {
        keyword: "CONNECT BY",
        syntax: "SELECT ... START WITH ... CONNECT BY PRIOR child = parent",
        description: "层级递归查询",
        category: "query",
        example: "SELECT employee_id, manager_id FROM employees START WITH manager_id IS NULL CONNECT BY PRIOR employee_id = manager_id",
    },
    { keyword: "START WITH", syntax: "START WITH condition", description: "层级查询的起始行条件", category: "query" },
    { keyword: "PRIOR", syntax: "CONNECT BY PRIOR child_col = parent_col", description: "在 CONNECT BY 中引用父行的列", category: "query" },
    { keyword: "PLS_INTEGER", syntax: "var_name PLS_INTEGER", description: "PL/SQL 兼容整数类型", category: "type" },
    { keyword: "BINARY_INTEGER", syntax: "var_name BINARY_INTEGER", description: "PL/SQL 兼容整数类型", category: "type" },
    { keyword: "BINARY_FLOAT", syntax: "BINARY_FLOAT", description: "单精度浮点类型", category: "type" },
    { keyword: "BINARY_DOUBLE", syntax: "BINARY_DOUBLE", description: "双精度浮点类型", category: "type" },
    {
        keyword: "VARCHAR2",
        syntax: "VARCHAR2(size [BYTE | CHAR])",
        description: "变长字符串（达梦推荐使用）",
        category: "type",
        example: "CREATE TABLE t (name VARCHAR2(100))",
    },
    { keyword: "NVARCHAR2", syntax: "NVARCHAR2(size)", description: "Unicode 变长字符串", category: "type" },
    {
        keyword: "NUMBER",
        syntax: "NUMBER [(precision [, scale])]",
        description: "数值类型，可指定精度与小数位",
        category: "type",
        example: "CREATE TABLE t (amount NUMBER(10, 2))",
    },
    { keyword: "CLOB", syntax: "CLOB", description: "字符大对象", category: "type" },
    { keyword: "NCLOB", syntax: "NCLOB", description: "Unicode 字符大对象", category: "type" },
    { keyword: "BFILE", syntax: "BFILE", description: "指向服务器文件系统中文件的只读 LOB 定位器", category: "type" },
    {
        keyword: "TIMESTAMP WITH TIME ZONE",
        syntax: "TIMESTAMP [(p)] WITH TIME ZONE",
        description: "带时区的 TIMESTAMP 类型",
        category: "type",
    },
    {
        keyword: "TIMESTAMP WITH LOCAL TIME ZONE",
        syntax: "TIMESTAMP [(p)] WITH LOCAL TIME ZONE",
        description: "存储时转库时区、读取时转会话时区的 TIMESTAMP",
        category: "type",
    },
    { keyword: "INTERVAL YEAR TO MONTH", syntax: "INTERVAL YEAR [(p)] TO MONTH", description: "年月间隔类型", category: "type" },
    { keyword: "INTERVAL DAY TO SECOND", syntax: "INTERVAL DAY [(dp)] TO SECOND [(sp)]", description: "日秒间隔类型", category: "type" },
    {
        keyword: "DECODE",
        syntax: "DECODE(expr, search1, result1 [, search2, result2, ...] [, default])",
        description: "条件取值函数",
        category: "auxiliary",
        example: "SELECT DECODE(status, 1, 'active', 0, 'inactive', 'unknown') FROM users",
    },
    {
        keyword: "NVL",
        syntax: "NVL(expr, default)",
        description: "若 expr 为 NULL 返回 default",
        category: "auxiliary",
        example: "SELECT NVL(nickname, real_name) FROM users",
    },
    {
        keyword: "NVL2",
        syntax: "NVL2(expr, value_if_not_null, value_if_null)",
        description: "根据 expr 是否为 NULL 返回不同值",
        category: "auxiliary",
    },
    {
        keyword: "LISTAGG",
        syntax: "LISTAGG(expr, separator) WITHIN GROUP (ORDER BY ...)",
        description: "将组内字符串连接为单个字符串",
        category: "auxiliary",
        example: "SELECT LISTAGG(name, ',') WITHIN GROUP (ORDER BY name) FROM employees",
    },
    {
        keyword: "MERGE",
        syntax: "MERGE INTO target USING source ON ... WHEN MATCHED THEN ... WHEN NOT MATCHED THEN ...",
        description: "根据源表对目标表执行 upsert/delete",
        category: "dml",
        example:
            "MERGE INTO target t USING source s ON (t.id = s.id) WHEN MATCHED THEN UPDATE SET t.name = s.name WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)",
    },
    {
        keyword: "PACKAGE",
        syntax: "CREATE OR REPLACE PACKAGE name IS ... END name;",
        description: "PL/SQL 兼容包规范",
        category: "ddl",
        example: "CREATE OR REPLACE PACKAGE pkg_util IS FUNCTION add(a INT, b INT) RETURN INT; END pkg_util;",
    },
    { keyword: "DM_HASH", syntax: "DM_HASH(expr)", description: "达梦专有哈希函数", category: "auxiliary" },
    { keyword: "DM_ENCRYPT", syntax: "DM_ENCRYPT(expr)", description: "达梦专有加密函数", category: "auxiliary" },
    { keyword: "TO_DM_DATE", syntax: "TO_DM_DATE(expr)", description: "达梦专有日期转换函数", category: "auxiliary" },
    { keyword: "XMLTYPE", syntax: "XMLTYPE", description: "XML 数据类型", category: "type" },
];
