import type { KeywordInfo } from "../../hover/HoverResolver";

// Oracle specific keyword info for hover/completion.
export const oracleKeywords: KeywordInfo[] = [
    {
        keyword: "DUAL",
        syntax: "SELECT expr FROM DUAL",
        description: "Oracle 提供的虚拟单行表，用于无需业务表的 SELECT",
        category: "query",
        example: "SELECT SYSDATE FROM DUAL",
    },
    {
        keyword: "ROWNUM",
        syntax: "WHERE ROWNUM <= n",
        description: "伪列，返回结果集中行的序号（在排序前分配）",
        category: "query",
        example: "SELECT * FROM employees WHERE ROWNUM <= 10",
    },
    { keyword: "ROWID", syntax: "SELECT ROWID, ... FROM table", description: "伪列，行的物理存储地址标识符", category: "query" },
    {
        keyword: "SYSDATE",
        syntax: "SYSDATE",
        description: "返回当前会话时区的日期时间",
        category: "auxiliary",
        example: "SELECT SYSDATE FROM DUAL",
    },
    { keyword: "SYSTIMESTAMP", syntax: "SYSTIMESTAMP", description: "返回数据库服务器时区的高精度时间戳", category: "auxiliary" },
    {
        keyword: "SEQUENCE",
        syntax: "CREATE SEQUENCE name START WITH n INCREMENT BY m",
        description: "用户定义的序列对象，通过 NEXTVAL/CURRVAL 取值",
        category: "ddl",
        example: "CREATE SEQUENCE seq_orders START WITH 1 INCREMENT BY 1",
    },
    {
        keyword: "NEXTVAL",
        syntax: "sequence.NEXTVAL",
        description: "取序列的下一个值",
        category: "auxiliary",
        example: "INSERT INTO orders(id) VALUES (seq_orders.NEXTVAL)",
    },
    { keyword: "CURRVAL", syntax: "sequence.CURRVAL", description: "取序列在当前会话的当前值（需先调用 NEXTVAL）", category: "auxiliary" },
    {
        keyword: "SYNONYM",
        syntax: "CREATE [OR REPLACE] [PUBLIC] SYNONYM name FOR object",
        description: "为对象创建别名",
        category: "ddl",
        example: "CREATE SYNONYM emp FOR hr.employees",
    },
    {
        keyword: "MINUS",
        syntax: "SELECT ... MINUS SELECT ...",
        description: "集合差运算（Oracle 等价于标准 SQL 的 EXCEPT）",
        category: "query",
        example: "SELECT id FROM a MINUS SELECT id FROM b",
    },
    {
        keyword: "CONNECT BY",
        syntax: "SELECT ... START WITH ... CONNECT BY PRIOR child = parent",
        description: "层级递归查询",
        category: "query",
        example: "SELECT employee_id, manager_id FROM employees START WITH manager_id IS NULL CONNECT BY PRIOR employee_id = manager_id",
    },
    { keyword: "START WITH", syntax: "START WITH condition", description: "层级查询的起始行条件", category: "query" },
    { keyword: "PRIOR", syntax: "CONNECT BY PRIOR child_col = parent_col", description: "在 CONNECT BY 中引用父行的列", category: "query" },
    { keyword: "NOCYCLE", syntax: "CONNECT BY NOCYCLE PRIOR ...", description: "层级查询遇到循环不报错并停止", category: "query" },
    {
        keyword: "PLS_INTEGER",
        syntax: "var_name PLS_INTEGER",
        description: "PL/SQL 专用整数类型（平台相关，比 NUMBER 快）",
        category: "type",
    },
    { keyword: "BINARY_INTEGER", syntax: "var_name BINARY_INTEGER", description: "PL/SQL 整数类型（跨平台兼容）", category: "type" },
    { keyword: "BINARY_FLOAT", syntax: "BINARY_FLOAT", description: "单精度浮点类型（IEEE 754）", category: "type" },
    { keyword: "BINARY_DOUBLE", syntax: "BINARY_DOUBLE", description: "双精度浮点类型（IEEE 754）", category: "type" },
    {
        keyword: "VARCHAR2",
        syntax: "VARCHAR2(size [BYTE | CHAR])",
        description: "变长字符串，Oracle 推荐使用（而非 VARCHAR）",
        category: "type",
        example: "CREATE TABLE t (name VARCHAR2(100))",
    },
    { keyword: "NVARCHAR2", syntax: "NVARCHAR2(size)", description: "Unicode 变长字符串", category: "type" },
    {
        keyword: "NUMBER",
        syntax: "NUMBER [(precision [, scale])]",
        description: "数值类型，可指定精度与小数位",
        category: "type",
        example: "CREATE TABLE t (amount NUMBER(10, 2))",
    },
    { keyword: "CLOB", syntax: "CLOB", description: "字符大对象（最大 128TB）", category: "type" },
    { keyword: "NCLOB", syntax: "NCLOB", description: "Unicode 字符大对象", category: "type" },
    { keyword: "BFILE", syntax: "BFILE", description: "指向服务器文件系统中文件的只读 LOB 定位器", category: "type" },
    {
        keyword: "TIMESTAMP WITH TIME ZONE",
        syntax: "TIMESTAMP [(p)] WITH TIME ZONE",
        description: "带时区的 TIMESTAMP 类型",
        category: "type",
    },
    {
        keyword: "TIMESTAMP WITH LOCAL TIME ZONE",
        syntax: "TIMESTAMP [(p)] WITH LOCAL TIME ZONE",
        description: "存储时转库时区、读取时转会话时区的 TIMESTAMP",
        category: "type",
    },
    { keyword: "INTERVAL YEAR TO MONTH", syntax: "INTERVAL YEAR [(p)] TO MONTH", description: "年月间隔类型", category: "type" },
    { keyword: "INTERVAL DAY TO SECOND", syntax: "INTERVAL DAY [(dp)] TO SECOND [(sp)]", description: "日秒间隔类型", category: "type" },
    {
        keyword: "DECODE",
        syntax: "DECODE(expr, search1, result1 [, search2, result2, ...] [, default])",
        description: "条件取值函数（等价于简单 CASE WHEN）",
        category: "auxiliary",
        example: "SELECT DECODE(status, 1, 'active', 0, 'inactive', 'unknown') FROM users",
    },
    {
        keyword: "NVL",
        syntax: "NVL(expr, default)",
        description: "若 expr 为 NULL 返回 default",
        category: "auxiliary",
        example: "SELECT NVL(nickname, real_name) FROM users",
    },
    {
        keyword: "NVL2",
        syntax: "NVL2(expr, value_if_not_null, value_if_null)",
        description: "根据 expr 是否为 NULL 返回不同值",
        category: "auxiliary",
    },
    {
        keyword: "LISTAGG",
        syntax: "LISTAGG(expr, separator) WITHIN GROUP (ORDER BY ...)",
        description: "将组内字符串连接为单个字符串",
        category: "auxiliary",
        example: "SELECT LISTAGG(name, ',') WITHIN GROUP (ORDER BY name) FROM employees",
    },
    { keyword: "CONNECT_BY_ROOT", syntax: "CONNECT_BY_ROOT col", description: "层级查询中返回根行的列值", category: "query" },
    {
        keyword: "SYS_CONNECT_BY_PATH",
        syntax: "SYS_CONNECT_BY_PATH(col, separator)",
        description: "层级查询中返回从根到当前行的列值路径",
        category: "auxiliary",
    },
    {
        keyword: "MERGE",
        syntax: "MERGE INTO target USING source ON ... WHEN MATCHED THEN ... WHEN NOT MATCHED THEN ...",
        description: "根据源表对目标表执行 upsert/delete",
        category: "dml",
        example:
            "MERGE INTO target t USING source s ON (t.id = s.id) WHEN MATCHED THEN UPDATE SET t.name = s.name WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)",
    },
    {
        keyword: "PACKAGE",
        syntax: "CREATE OR REPLACE PACKAGE name IS ... END name;",
        description: "PL/SQL 包规范，封装过程/函数/变量",
        category: "ddl",
        example: "CREATE OR REPLACE PACKAGE pkg_util IS FUNCTION add(a INT, b INT) RETURN INT; END pkg_util;",
    },
    {
        keyword: "PRAGMA",
        syntax: "PRAGMA autonomous_transaction | exception_init(...) | ...",
        description: "PL/SQL 编译指令",
        category: "ddl",
    },
    {
        keyword: "AUTONOMOUS_TRANSACTION",
        syntax: "PRAGMA AUTONOMOUS_TRANSACTION",
        description: "声明自治事务，独立于主事务提交/回滚",
        category: "ddl",
    },
    { keyword: "XMLTYPE", syntax: "XMLTYPE", description: "XML 数据类型", category: "type" },
];
