import type { KeywordInfo } from "../../hover/HoverResolver";

// SQL Server (T-SQL) specific keyword info for hover/completion.
export const sqlserverKeywords: KeywordInfo[] = [
    {
        keyword: "TOP",
        syntax: "SELECT TOP (n) [PERCENT] [WITH TIES] ...",
        description: "限制查询返回的行数，可按百分比或并列行返回",
        category: "query",
        example: "SELECT TOP 10 * FROM employees",
    },
    {
        keyword: "OFFSET",
        syntax: "ORDER BY ... OFFSET n ROWS [FETCH NEXT m ROWS ONLY]",
        description: "分页跳过指定行数（需配合 ORDER BY 与 FETCH）",
        category: "query",
        example: "SELECT * FROM employees ORDER BY id OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
    },
    {
        keyword: "FETCH",
        syntax: "OFFSET n ROWS FETCH NEXT m ROWS ONLY",
        description: "在 OFFSET 之后取指定行数，实现分页",
        category: "query",
    },
    {
        keyword: "OUTPUT",
        syntax: "INSERT/UPDATE/DELETE ... OUTPUT inserted.col, deleted.col",
        description: "在 DML 语句中返回受影响行的列（类似 RETURNING）",
        category: "dml",
        example: "DELETE FROM employees OUTPUT deleted.id WHERE status = 'inactive'",
    },
    {
        keyword: "MERGE",
        syntax: "MERGE INTO target USING source ON ... WHEN MATCHED THEN ... WHEN NOT MATCHED THEN ...",
        description: "根据源表对目标表执行 upsert/delete 操作",
        category: "dml",
        example:
            "MERGE INTO target t USING source s ON t.id = s.id WHEN MATCHED THEN UPDATE SET t.name = s.name WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name);",
    },
    {
        keyword: "PIVOT",
        syntax: "SELECT ... FROM (subquery) PIVOT (agg(col) FOR pivot_col IN (...)) AS p",
        description: "将行旋转为列的透视操作",
        category: "query",
        example: "SELECT * FROM (SELECT year, quarter, amount FROM sales) s PIVOT (SUM(amount) FOR quarter IN ([Q1],[Q2],[Q3],[Q4])) p",
    },
    {
        keyword: "UNPIVOT",
        syntax: "SELECT ... FROM source UNPIVOT (value_col FOR name_col IN (...)) AS u",
        description: "将列旋转为行的逆透视操作",
        category: "query",
    },
    {
        keyword: "ROW_NUMBER",
        syntax: "ROW_NUMBER() OVER (ORDER BY ...)",
        description: "为结果集行生成连续序号",
        category: "auxiliary",
        example: "SELECT ROW_NUMBER() OVER (ORDER BY created_at) AS rn, * FROM employees",
    },
    {
        keyword: "IDENTITY",
        syntax: "col_name INT IDENTITY(seed, increment)",
        description: "自增列属性",
        category: "type",
        example: "CREATE TABLE t (id INT IDENTITY(1,1) PRIMARY KEY)",
    },
    {
        keyword: "NVARCHAR",
        syntax: "NVARCHAR(n | MAX)",
        description: "Unicode 变长字符串，MAX 表示大值类型",
        category: "type",
        example: "CREATE TABLE t (name NVARCHAR(100))",
    },
    { keyword: "DATETIME2", syntax: "DATETIME2 [(precision)]", description: "高精度日期时间类型（0-7 位小数秒）", category: "type" },
    { keyword: "DATETIMEOFFSET", syntax: "DATETIMEOFFSET [(precision)]", description: "带时区偏移的日期时间类型", category: "type" },
    { keyword: "MONEY", syntax: "MONEY", description: "货币类型（8 字节，精度 19,4）", category: "type" },
    {
        keyword: "UNIQUEIDENTIFIER",
        syntax: "UNIQUEIDENTIFIER",
        description: "GUID 类型（16 字节）",
        category: "type",
        example: "CREATE TABLE t (id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY)",
    },
    { keyword: "SQL_VARIANT", syntax: "SQL_VARIANT", description: "可存储多种基础类型的变体类型", category: "type" },
    {
        keyword: "TRY_CONVERT",
        syntax: "TRY_CONVERT(data_type, expr [, style])",
        description: "尝试类型转换，失败返回 NULL",
        category: "auxiliary",
        example: "SELECT TRY_CONVERT(INT, 'abc')",
    },
    { keyword: "TRY_CAST", syntax: "TRY_CAST(expr AS data_type)", description: "尝试类型转换，失败返回 NULL", category: "auxiliary" },
    {
        keyword: "STRING_AGG",
        syntax: "STRING_AGG(expr, separator) [WITHIN GROUP (ORDER BY ...)]",
        description: "将组内字符串连接为单个字符串",
        category: "auxiliary",
        example: "SELECT STRING_AGG(name, ',') WITHIN GROUP (ORDER BY name) FROM employees",
    },
    {
        keyword: "IIF",
        syntax: "IIF(boolean_expr, true_value, false_value)",
        description: "内联条件表达式（等价于简化的 CASE WHEN）",
        category: "auxiliary",
        example: "SELECT IIF(score >= 60, 'pass', 'fail') FROM exams",
    },
    { keyword: "CHOOSE", syntax: "CHOOSE(index, val1, val2, ...)", description: "按索引从列表返回值", category: "auxiliary" },
    {
        keyword: "SWITCHOFFSET",
        syntax: "SWITCHOFFSET(datetimeoffset, timezone)",
        description: "将 DATETIMEOFFSET 值切换到指定时区",
        category: "auxiliary",
    },
    {
        keyword: "JSON_VALUE",
        syntax: "JSON_VALUE(json_expr, path)",
        description: "从 JSON 字符串提取标量值",
        category: "auxiliary",
        example: "SELECT JSON_VALUE(data, '$.user.name') FROM logs",
    },
    { keyword: "JSON_QUERY", syntax: "JSON_QUERY(json_expr, path)", description: "从 JSON 字符串提取对象或数组", category: "auxiliary" },
    {
        keyword: "OPENJSON",
        syntax: "OPENJSON(json_expr [, path]) WITH (col type path, ...)",
        description: "将 JSON 数组解析为行集",
        category: "auxiliary",
    },
    {
        keyword: "FOR XML",
        syntax: "SELECT ... FOR XML PATH | AUTO | RAW | EXPLICIT",
        description: "将查询结果序列化为 XML",
        category: "query",
        example: "SELECT id, name FROM employees FOR XML PATH('employee')",
    },
    {
        keyword: "FOR JSON",
        syntax: "SELECT ... FOR JSON PATH | AUTO",
        description: "将查询结果序列化为 JSON",
        category: "query",
        example: "SELECT id, name FROM employees FOR JSON PATH",
    },
    {
        keyword: "WITH (NOLOCK)",
        syntax: "FROM table WITH (NOLOCK)",
        description: "表提示：允许脏读（等价于 READ UNCOMMITTED）",
        category: "hint",
        example: "SELECT * FROM employees WITH (NOLOCK)",
    },
    {
        keyword: "SEQUENCE",
        syntax: "CREATE SEQUENCE name [AS type] START WITH n [INCREMENT BY m]",
        description: "用户定义的序列对象",
        category: "ddl",
        example: "CREATE SEQUENCE seq_orders START WITH 1 INCREMENT BY 1",
    },
    {
        keyword: "CROSS APPLY",
        syntax: "FROM left CROSS APPLY right",
        description: "对左表每行调用右表值函数并合并结果（类似 INNER JOIN）",
        category: "query",
        example: "SELECT * FROM employees e CROSS APPLY dbo.GetSalary(e.id)",
    },
    {
        keyword: "OUTER APPLY",
        syntax: "FROM left OUTER APPLY right",
        description: "对左表每行调用右表值函数并保留无匹配的左行（类似 LEFT JOIN）",
        category: "query",
    },
];
