import type { FunctionSignature } from '../../completion'

export const functions: string[] = [
    // aggregate
    'AVG',
    'COUNT',
    'GROUP_CONCAT',
    'MAX',
    'MIN',
    'SUM',
    'TOTAL',

    // window
    'CUME_DIST',
    'DENSE_RANK',
    'FIRST_VALUE',
    'LAG',
    'LAST_VALUE',
    'LEAD',
    'NTH_VALUE',
    'NTILE',
    'PERCENT_RANK',
    'RANK',
    'ROW_NUMBER',

    // string
    'CHAR',
    'CONCAT',
    'GLOB',
    'HEX',
    'INSTR',
    'INSERT',
    'LENGTH',
    'LIKE',
    'LOWER',
    'LTRIM',
    'NULLIF',
    'PRINTF',
    'QUOTE',
    'RANDOMBLOB',
    'REPLACE',
    'ROUND',
    'RTRIM',
    'SOUNDEX',
    'SQLITE_COMPILEOPTION_GET',
    'SQLITE_COMPILEOPTION_USED',
    'SQLITE_OFFSET',
    'SQLITE_SOURCE_ID',
    'SQLITE_VERSION',
    'SUBSTR',
    'SUBSTRING',
    'TOTAL_CHANGES',
    'TRIM',
    'TYPEOF',
    'UNICODE',
    'UNHEX',
    'UPPER',
    'ZEROBLOB',

    // date
    'DATE',
    'DATETIME',
    'JULIANDAY',
    'STRFTIME',
    'TIME',
    'CHANGES',

    // math
    'ABS',
    'ACOS',
    'ACOSH',
    'ASIN',
    'ASINH',
    'ATAN',
    'ATAN2',
    'ATANH',
    'CEIL',
    'CEILING',
    'COS',
    'COSH',
    'DEGREES',
    'EXP',
    'FLOOR',
    'LN',
    'LOG',
    'LOG10',
    'LOG2',
    'MOD',
    'PI',
    'POW',
    'POWER',
    'RADIANS',
    'SIGN',
    'SIN',
    'SINH',
    'SQRT',
    'TAN',
    'TANH',
    'TRUNC',

    // json
    'JSON',
    'JSON_ARRAY',
    'JSON_ARRAY_LENGTH',
    'JSON_EACH',
    'JSON_EXTRACT',
    'JSON_GROUP_ARRAY',
    'JSON_GROUP_OBJECT',
    'JSON_INSERT',
    'JSON_PATCH',
    'JSON_QUOTE',
    'JSON_REMOVE',
    'JSON_REPLACE',
    'JSON_SET',
    'JSON_TYPE',
    'JSON_VALID',
    'JSONB',
    'JSONB_ARRAY',
    'JSONB_EXTRACT',
    'JSONB_INSERT',
    'JSONB_PATCH',
    'JSONB_REMOVE',
    'JSONB_REPLACE',
    'JSONB_SET',
    'JSONB_TYPE',

    // conditional
    'COALESCE',
    'IFNULL',
    'IIF',

    // flow
    'CASE',
    'LIKELIHOOD',
    'LIKELY',
    'UNLIKELY',

    // window frame
    'EXCLUDE_GROUP',
    'EXCLUDE_NO_OTHERS',
    'EXCLUDE_TIES',
    'EXCLUDE_CURRENT_ROW',
    'FILTER',
    'FIRST_VALUE',
    'GROUPS',
    'LAST_VALUE',
    'RANGE',
    'ROWS',
    'UNBOUNDED',
];

export const functionSignatures: FunctionSignature[] = [
    // --- AGGREGATE (7) ---
    { name: 'AVG', params: ['T col'], returnType: 'double', description: '返回列的平均值', category: 'aggregate' },
    { name: 'COUNT', params: ['*|T col'], returnType: 'bigint', description: '返回行数或非 NULL 行数', category: 'aggregate' },
    { name: 'GROUP_CONCAT', params: ['T col', 'string sep'], returnType: 'string', description: '将组内值用分隔符连接为字符串', category: 'aggregate' },
    { name: 'MAX', params: ['T col'], returnType: 'T', description: '返回列的最大值', category: 'aggregate' },
    { name: 'MIN', params: ['T col'], returnType: 'T', description: '返回列的最小值', category: 'aggregate' },
    { name: 'SUM', params: ['T col'], returnType: 'T', description: '返回列的总和', category: 'aggregate' },
    { name: 'TOTAL', params: ['T col'], returnType: 'double', description: '返回列的总和（始终返回浮点数，NULL 返回 0.0）', category: 'aggregate' },

    // --- WINDOW (10) ---
    { name: 'CUME_DIST', params: [], returnType: 'double', description: '返回累积分布值（0-1）', category: 'window' },
    { name: 'DENSE_RANK', params: [], returnType: 'int', description: '返回排序名次（相同值同名次，无间隔）', category: 'window' },
    { name: 'FIRST_VALUE', params: ['T col'], returnType: 'T', description: '返回窗口内第一行的值', category: 'window' },
    { name: 'LAG', params: ['T col', 'int offset', 'T default'], returnType: 'T', description: '返回当前行之前 offset 行的值', category: 'window' },
    { name: 'LAST_VALUE', params: ['T col'], returnType: 'T', description: '返回窗口内最后一行的值', category: 'window' },
    { name: 'LEAD', params: ['T col', 'int offset', 'T default'], returnType: 'T', description: '返回当前行之后 offset 行的值', category: 'window' },
    { name: 'NTH_VALUE', params: ['T col', 'int n'], returnType: 'T', description: '返回窗口内第 n 行的值', category: 'window' },
    { name: 'NTILE', params: ['int n'], returnType: 'int', description: '将行分配到 n 个桶中，返回桶编号', category: 'window' },
    { name: 'PERCENT_RANK', params: [], returnType: 'double', description: '返回相对排名百分比（0-1）', category: 'window' },
    { name: 'RANK', params: [], returnType: 'int', description: '返回排序名次（相同值同名次，有间隔）', category: 'window' },
    { name: 'ROW_NUMBER', params: [], returnType: 'int', description: '返回行号（从 1 开始，无重复）', category: 'window' },

    // --- STRING (12) ---
    { name: 'CHAR', params: ['int x1', 'int x2', '...'], returnType: 'string', description: '将 Unicode 码点转换为字符', category: 'string' },
    { name: 'CONCAT', params: ['string str1', 'string str2', '...'], returnType: 'string', description: '连接多个字符串', category: 'string' },
    { name: 'INSTR', params: ['string str', 'string substr'], returnType: 'int', description: '返回子串首次出现的位置（从 1 开始）', category: 'string' },
    { name: 'LENGTH', params: ['string str'], returnType: 'int', description: '返回字符串的长度（字符数）', category: 'string' },
    { name: 'LOWER', params: ['string str'], returnType: 'string', description: '返回全小写的字符串', category: 'string' },
    { name: 'LTRIM', params: ['string str', 'string chars'], returnType: 'string', description: '去除字符串左侧指定字符（默认空白）', category: 'string' },
    { name: 'PRINTF', params: ['string format', '... values'], returnType: 'string', description: '返回格式化后的字符串（C 语言 printf 风格）', category: 'string' },
    { name: 'REPLACE', params: ['string str', 'string find', 'string replacement'], returnType: 'string', description: '替换字符串中所有匹配的子串', category: 'string' },
    { name: 'RTRIM', params: ['string str', 'string chars'], returnType: 'string', description: '去除字符串右侧指定字符（默认空白）', category: 'string' },
    { name: 'SUBSTR', params: ['string str', 'int start', 'int length'], returnType: 'string', description: '返回从 start 开始指定长度的子串', category: 'string' },
    { name: 'TRIM', params: ['string str', 'string chars'], returnType: 'string', description: '去除字符串两侧指定字符（默认空白）', category: 'string' },
    { name: 'UPPER', params: ['string str'], returnType: 'string', description: '返回全大写的字符串', category: 'string' },

    // --- DATE (6) ---
    { name: 'DATE', params: ['string timestring', 'string modifier', '...'], returnType: 'string', description: '返回日期部分', category: 'date' },
    { name: 'DATETIME', params: ['string timestring', 'string modifier', '...'], returnType: 'string', description: '返回日期时间部分', category: 'date' },
    { name: 'JULIANDAY', params: ['string timestring', 'string modifier', '...'], returnType: 'double', description: '返回儒略日数', category: 'date' },
    { name: 'STRFTIME', params: ['string format', 'string timestring', 'string modifier', '...'], returnType: 'string', description: '按指定格式将时间转为字符串', category: 'date' },
    { name: 'TIME', params: ['string timestring', 'string modifier', '...'], returnType: 'string', description: '返回时间部分', category: 'date' },
    { name: 'CHANGES', params: [], returnType: 'int', description: '返回最近一条 SQL 语句影响的行数', category: 'date' },

    // --- MATH (15) ---
    { name: 'ABS', params: ['T a'], returnType: 'T', description: '返回数值的绝对值', category: 'math' },
    { name: 'ACOS', params: ['double a'], returnType: 'double', description: '返回反余弦值', category: 'math' },
    { name: 'ASIN', params: ['double a'], returnType: 'double', description: '返回反正弦值', category: 'math' },
    { name: 'ATAN', params: ['double a'], returnType: 'double', description: '返回反正切值', category: 'math' },
    { name: 'ATAN2', params: ['double y', 'double x'], returnType: 'double', description: '返回 y/x 的反正切值', category: 'math' },
    { name: 'CEIL', params: ['double a'], returnType: 'bigint', description: '返回不小于 a 的最小整数（向上取整）', category: 'math' },
    { name: 'CEILING', params: ['double a'], returnType: 'bigint', description: 'CEIL 的别名，向上取整', category: 'math' },
    { name: 'COS', params: ['double a'], returnType: 'double', description: '返回余弦值', category: 'math' },
    { name: 'EXP', params: ['double a'], returnType: 'double', description: '返回 e 的 a 次幂', category: 'math' },
    { name: 'FLOOR', params: ['double a'], returnType: 'bigint', description: '返回不大于 a 的最大整数（向下取整）', category: 'math' },
    { name: 'LN', params: ['double a'], returnType: 'double', description: '返回 a 的自然对数', category: 'math' },
    { name: 'LOG', params: ['double a'], returnType: 'double', description: '返回 a 的自然对数', category: 'math' },
    { name: 'LOG2', params: ['double a'], returnType: 'double', description: '返回 a 的以 2 为底的对数', category: 'math' },
    { name: 'MOD', params: ['T a', 'T b'], returnType: 'T', description: '返回 a 除以 b 的余数', category: 'math' },
    { name: 'PI', params: [], returnType: 'double', description: '返回圆周率 π', category: 'math' },
    { name: 'POW', params: ['double a', 'double b'], returnType: 'double', description: '返回 a 的 b 次幂', category: 'math' },
    { name: 'POWER', params: ['double a', 'double b'], returnType: 'double', description: 'POW 的别名，返回 a 的 b 次幂', category: 'math' },
    { name: 'ROUND', params: ['double a', 'int d'], returnType: 'double', description: '将 a 四舍五入到 d 位小数', category: 'math' },
    { name: 'SIGN', params: ['double a'], returnType: 'double', description: '返回 a 的符号（1.0/0.0/-1.0）', category: 'math' },
    { name: 'SQRT', params: ['double a'], returnType: 'double', description: '返回 a 的平方根', category: 'math' },
    { name: 'TRUNC', params: ['double a', 'int d'], returnType: 'double', description: '截断 a 到 d 位小数', category: 'math' },

    // --- JSON (10) ---
    { name: 'JSON', params: ['string json_str'], returnType: 'string', description: '验证并返回 JSON 字符串的规范形式', category: 'json' },
    { name: 'JSON_ARRAY', params: ['... values'], returnType: 'string', description: '从参数构建 JSON 数组', category: 'json' },
    { name: 'JSON_EXTRACT', params: ['string json', 'string path'], returnType: 'string', description: '从 JSON 中按路径提取值', category: 'json' },
    { name: 'JSON_INSERT', params: ['string json', 'string path', 'T value'], returnType: 'string', description: '在 JSON 中插入值（不覆盖已有路径）', category: 'json' },
    { name: 'JSON_REPLACE', params: ['string json', 'string path', 'T value'], returnType: 'string', description: '替换 JSON 中已有路径的值', category: 'json' },
    { name: 'JSON_SET', params: ['string json', 'string path', 'T value'], returnType: 'string', description: '在 JSON 中设置值（插入或替换）', category: 'json' },
    { name: 'JSON_TYPE', params: ['string json', 'string path'], returnType: 'string', description: '返回 JSON 路径处的值类型', category: 'json' },
    { name: 'JSON_VALID', params: ['string json'], returnType: 'int', description: '判断字符串是否为合法 JSON', category: 'json' },
    { name: 'JSON_GROUP_ARRAY', params: ['T col'], returnType: 'string', description: '聚合为 JSON 数组', category: 'json' },
    { name: 'JSON_GROUP_OBJECT', params: ['string key', 'T value'], returnType: 'string', description: '聚合为 JSON 对象', category: 'json' },

    // --- CONDITIONAL (4) ---
    { name: 'COALESCE', params: ['T v1', 'T v2', '...'], returnType: 'T', description: '返回参数列表中第一个非 NULL 值', category: 'conditional' },
    { name: 'IFNULL', params: ['T a', 'T b'], returnType: 'T', description: '若 a 为 NULL 则返回 b，否则返回 a', category: 'conditional' },
    { name: 'IIF', params: ['boolean condition', 'T true_val', 'T false_val'], returnType: 'T', description: '根据条件返回不同的值', category: 'conditional' },
    { name: 'NULLIF', params: ['T a', 'T b'], returnType: 'T', description: '若 a=b 则返回 NULL，否则返回 a', category: 'conditional' },
];
