// Oracle SQL and PL/SQL keywords.
// Reference: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Reserved-Words.html
// Note: %TYPE and %ROWTYPE are PL/SQL attribute references (e.g. table.column%TYPE).
// They are included here for completeness, but the lexer may decompose them into
// '%' operator + 'TYPE'/'ROWTYPE' identifier tokens since '%' is not a word character.

export const keywords: string[] = [
    // --- Oracle specific keywords ---
    'AUTONOMOUS_TRANSACTION',
    'BFILE',
    'BINARY_INTEGER',
    'BODY',
    'COMPILE',
    'CONNECT',
    'DBLINK',
    'DUAL',
    'EXCEPTION_INIT',
    'INSTEAD',
    'MINUS',
    'NCHAR',
    'NCLOB',
    'NVARCHAR2',
    'PACKAGE',
    'PLS_INTEGER',
    'PRAGMA',
    'PRIOR',
    'RESTRICT_REFERENCES',
    'ROWID',
    'ROWNUM',
    'SEQUENCE',
    'SPECIFICATION',
    'START',
    'SYNONYM',
    'SYSDATE',
    'VARCHAR2',
    'XMLTYPE',
    // %TYPE / %ROWTYPE: PL/SQL attribute references
    '%TYPE',
    '%ROWTYPE',

    // --- Common SQL keywords ---
    'ACCESS',
    'ADD',
    'AFTER',
    'ALL',
    'ALTER',
    'AND',
    'ANY',
    'AS',
    'ASC',
    'AUDIT',
    'BEFORE',
    'BEGIN',
    'BETWEEN',
    'BY',
    'CACHE',
    'CALL',
    'CASCADE',
    'CASE',
    'CHAR',
    'CHECK',
    'CLOSE',
    'CLUSTER',
    'COLUMN',
    'COMMENT',
    'COMMIT',
    'COMPRESS',
    'CONSTRAINT',
    'CONTINUE',
    'CREATE',
    'CROSS',
    'CURSOR',
    'DATABASE',
    'DATE',
    'DEC',
    'DECIMAL',
    'DECLARE',
    'DEFAULT',
    'DELETE',
    'DESC',
    'DISTINCT',
    'DO',
    'DROP',
    'ELSE',
    'ELSIF',
    'END',
    'ESCAPE',
    'EXCLUSIVE',
    'EXCEPTION',
    'EXECUTE',
    'EXISTS',
    'EXIT',
    'EXTERNAL',
    'FETCH',
    'FLOAT',
    'FOR',
    'FORCE',
    'FOREIGN',
    'FROM',
    'FULL',
    'FUNCTION',
    'GOTO',
    'GRANT',
    'GROUP',
    'HAVING',
    'IDENTIFIED',
    'IF',
    'IMMEDIATE',
    'IN',
    'INCREMENT',
    'INDEX',
    'INITIAL',
    'INITIALIZE',
    'INSERT',
    'INTEGER',
    'INTERSECT',
    'INTERVAL',
    'INTO',
    'IS',
    'JOIN',
    'KEY',
    'LANGUAGE',
    'LEADING',
    'LEFT',
    'LEVEL',
    'LIKE',
    'LIMIT',
    'LOCK',
    'LONG',
    'LOOP',
    'MATCH',
    'MAXVALUE',
    'MINVALUE',
    'MODE',
    'MODIFY',
    'NATURAL',
    'NEW',
    'NEXT',
    'NO',
    'NOAUDIT',
    'NOCOMPRESS',
    'NOT',
    'NOWAIT',
    'NULL',
    'NULLIF',
    'NUMBER',
    'OF',
    'OFFLINE',
    'OLD',
    'ON',
    'ONLINE',
    'ONLY',
    'OPEN',
    'OPTION',
    'OR',
    'ORDER',
    'OUT',
    'OUTER',
    'OVERLAPS',
    'PARALLEL',
    'PARTITION',
    'PCTFREE',
    'PCTUSED',
    'PRECISION',
    'PRIMARY',
    'PRIOR',
    'PRIVILEGES',
    'PROCEDURE',
    'PUBLIC',
    'RAISE',
    'RANGE',
    'RAW',
    'READ',
    'REAL',
    'RECORD',
    'REF',
    'REFERENCES',
    'RELEASE',
    'RENAME',
    'REPEAT',
    'REPLACE',
    'RESOURCE',
    'RETURN',
    'RETURNING',
    'REVOKE',
    'RIGHT',
    'ROLLBACK',
    'ROW',
    'ROWS',
    'SAVEPOINT',
    'SCHEMA',
    'SELECT',
    'SEPARATE',
    'SESSION',
    'SET',
    'SHARE',
    'SMALLINT',
    'SPACE',
    'SQL',
    'SUBTYPE',
    'SUCCESSFUL',
    'TABLE',
    'TABLESPACE',
    'THEN',
    'TIMESTAMP',
    'TO',
    'TRIGGER',
    'TYPE',
    'UID',
    'UNION',
    'UNIQUE',
    'UPDATE',
    'USER',
    'USE',
    'USING',
    'VALIDATE',
    'VALUES',
    'VARCHAR',
    'VIEW',
    'WHEN',
    'WHENEVER',
    'WHERE',
    'WHILE',
    'WITH',
    'WORK',
    'WRITE',
    'ZONE',
];

export const dataTypes: string[] = [
    // https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html
    // Character types
    'CHAR',
    'NCHAR',
    'VARCHAR2',
    'NVARCHAR2',
    'CLOB',
    'NCLOB',
    'LONG',
    'LONG RAW',
    // Numeric types
    'NUMBER',
    'BINARY_FLOAT',
    'BINARY_DOUBLE',
    'PLS_INTEGER',
    'BINARY_INTEGER',
    'SIMPLE_INTEGER',
    // Date/time types
    'DATE',
    'TIMESTAMP',
    'TIMESTAMP WITH TIME ZONE',
    'TIMESTAMP WITH LOCAL TIME ZONE',
    'INTERVAL YEAR TO MONTH',
    'INTERVAL DAY TO SECOND',
    // LOB types
    'BFILE',
    'BLOB',
    // Raw types
    'RAW',
    // Row types
    'ROWID',
    'UROWID',
    // Other types
    'XMLTYPE',
    'BOOLEAN',
    'MLSLABEL',
];
