/**
 * Build script: compiles snippet JSON files into a TypeScript module.
 *
 * Reads all JSON files from the snippets/ directory and generates
 * src/completion/generated/snippetData.ts that exports the snippet
 * data as a typed object, eliminating runtime file I/O.
 *
 * Usage: npx tsx scripts/generate-snippets.ts
 */

import * as fs from 'fs'
import * as path from 'path'

interface SnippetDef {
    prefix: string
    body: string[]
    description: string
}

const PROJECT_ROOT = path.resolve(__dirname, '..')
const SNIPPETS_DIR = path.join(PROJECT_ROOT, 'snippets')
const OUTPUT_DIR = path.join(PROJECT_ROOT, 'src', 'completion', 'generated')
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'snippetData.ts')

function main(): void {
    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true })
    }

    // Read all JSON files from snippets directory
    const files = fs.readdirSync(SNIPPETS_DIR).filter(f => f.endsWith('.json'))

    const data: Record<string, Record<string, SnippetDef>> = {}

    for (const file of files) {
        const dialectName = path.basename(file, '.json')
        const filePath = path.join(SNIPPETS_DIR, file)
        const content = fs.readFileSync(filePath, 'utf-8')
        try {
            data[dialectName] = JSON.parse(content) as Record<string, SnippetDef>
        } catch (e) {
            console.error(`Failed to parse ${file}:`, e)
            process.exit(1)
        }
    }

    // Generate TypeScript file
    const lines: string[] = [
        '// Auto-generated by scripts/generate-snippets.ts — do not edit manually',
        'export interface SnippetDef { prefix: string; body: string[]; description: string }',
        '',
        'export const snippetData: Record<string, Record<string, SnippetDef>> = '
            + JSON.stringify(data, null, 2)
            + ' as const',
        '',
    ]

    fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')

    const dialectCount = Object.keys(data).length
    const totalSnippets = Object.values(data).reduce((sum, d) => sum + Object.keys(d).length, 0)
    console.log(`Generated ${OUTPUT_FILE} (${dialectCount} dialects, ${totalSnippets} snippets)`)
}

main()
